import type { LoanDocument } from '@/types';
import type { ComparisonResult } from '@/types';
import type { DocumentPreviewData } from '@/components/documents';

export const mockDocuments: LoanDocument[] = [
  {
    id: '1',
    organization_id: 'org-1',
    uploaded_by: 'user-1',
    uploaded_at: '2024-12-05T10:30:00Z',
    original_filename: 'Facility Agreement - Project Apollo.pdf',
    storage_path: '/documents/1.pdf',
    document_type: 'facility_agreement',
    processing_status: 'completed',
    extraction_version: 1,
    raw_text: null,
    page_count: 245,
    file_size: 2500000,
    error_message: null,
    borrower_name: 'Apollo Industries Inc.',
    created_at: '2024-12-05T10:30:00Z',
    updated_at: '2024-12-05T10:35:00Z',
  },
  {
    id: '2',
    organization_id: 'org-1',
    uploaded_by: 'user-1',
    uploaded_at: '2024-12-04T14:20:00Z',
    original_filename: 'Amendment No. 1 - XYZ Corp Term Loan.docx',
    storage_path: '/documents/2.docx',
    document_type: 'amendment',
    processing_status: 'completed',
    extraction_version: 1,
    raw_text: null,
    page_count: 45,
    file_size: 850000,
    error_message: null,
    borrower_name: 'XYZ Corporation',
    created_at: '2024-12-04T14:20:00Z',
    updated_at: '2024-12-04T14:25:00Z',
  },
  {
    id: '3',
    organization_id: 'org-1',
    uploaded_by: 'user-2',
    uploaded_at: '2024-12-03T09:15:00Z',
    original_filename: 'Consent Request - ABC Holdings.pdf',
    storage_path: '/documents/3.pdf',
    document_type: 'consent',
    processing_status: 'processing',
    extraction_version: 1,
    raw_text: null,
    page_count: null,
    file_size: 1200000,
    error_message: null,
    borrower_name: 'ABC Holdings Ltd.',
    created_at: '2024-12-03T09:15:00Z',
    updated_at: '2024-12-03T09:15:00Z',
  },
  {
    id: '4',
    organization_id: 'org-1',
    uploaded_by: 'user-1',
    uploaded_at: '2024-12-02T16:45:00Z',
    original_filename: 'Revolving Credit Agreement - Neptune Ltd.pdf',
    storage_path: '/documents/4.pdf',
    document_type: 'facility_agreement',
    processing_status: 'review_required',
    extraction_version: 1,
    raw_text: null,
    page_count: 312,
    file_size: 3800000,
    error_message: 'Low confidence extraction for some fields',
    borrower_name: 'Neptune Ltd.',
    created_at: '2024-12-02T16:45:00Z',
    updated_at: '2024-12-02T17:00:00Z',
  },
  {
    id: '5',
    organization_id: 'org-1',
    uploaded_by: 'user-3',
    uploaded_at: '2024-12-01T11:00:00Z',
    original_filename: 'Assignment Agreement - Delta Corp.pdf',
    storage_path: '/documents/5.pdf',
    document_type: 'assignment',
    processing_status: 'failed',
    extraction_version: 1,
    raw_text: null,
    page_count: null,
    file_size: 950000,
    error_message: 'Unable to parse document structure',
    borrower_name: 'Delta Corp.',
    created_at: '2024-12-01T11:00:00Z',
    updated_at: '2024-12-01T11:05:00Z',
  },
];



export const mockComparisonDocuments = [
  { id: '1', name: 'Facility Agreement - Project Apollo.pdf', date: '2024-12-05' },
  { id: '2', name: 'Amendment No. 1 - Project Apollo.docx', date: '2024-12-04' },
  { id: '3', name: 'Revolving Credit Agreement - Neptune Ltd.pdf', date: '2024-12-02' },
  { id: '4', name: 'Term Loan Agreement - XYZ Corp.pdf', date: '2024-12-01' },
];

// Preview data for completed documents (keyed by document id)
export const mockDocumentPreviewData: Record<string, DocumentPreviewData> = {
  '1': {
    facilityName: 'Project Apollo Senior Secured Term Loan',
    totalCommitment: 500000000,
    currency: 'USD',
    maturityDate: '2029-11-20',
    confidenceScore: 0.96,
  },
  '2': {
    facilityName: 'XYZ Corp Term Loan Facility',
    totalCommitment: 250000000,
    currency: 'USD',
    maturityDate: '2028-06-15',
    confidenceScore: 0.91,
  },
};

export const mockComparisonResult: ComparisonResult = {
  document1: { id: '1', name: 'Facility Agreement - Project Apollo.pdf' },
  document2: { id: '2', name: 'Amendment No. 1 - Project Apollo.docx' },
  differences: [
    {
      category: 'Financial Terms',
      field: 'Total Commitments',
      document1Value: '$500,000,000',
      document2Value: '$550,000,000',
      changeType: 'modified',
    },
    {
      category: 'Financial Terms',
      field: 'Initial Margin',
      document1Value: '3.25%',
      document2Value: '3.00%',
      changeType: 'modified',
    },
    {
      category: 'Key Dates',
      field: 'Maturity Date',
      document1Value: 'November 20, 2029',
      document2Value: 'November 20, 2030',
      changeType: 'modified',
    },
    {
      category: 'Covenants',
      field: 'Maximum Leverage Ratio',
      document1Value: '4.50x',
      document2Value: '5.00x',
      changeType: 'modified',
    },
    {
      category: 'Covenants',
      field: 'Annual CapEx Limit',
      document1Value: '$50,000,000',
      document2Value: null,
      changeType: 'removed',
    },
    {
      category: 'Parties',
      field: 'Lender: Pacific Finance Ltd',
      document1Value: '20%',
      document2Value: '15%',
      changeType: 'modified',
    },
    {
      category: 'Parties',
      field: 'Lender: Asian Credit Corp',
      document1Value: null,
      document2Value: '5%',
      changeType: 'added',
    },
  ],
  impactAnalysis: 'The amendment provides more favorable terms to the borrower with increased facility size, reduced margin, extended maturity, and loosened covenants.',
};
