import type {
  AutopilotBreachPrediction,
  MarketSignal,
  TransactionPatternSignal,
  NewsSentimentSignal,
  BenchmarkSignal,
  RemediationStrategy,
  AutopilotNotification,
  AutopilotDashboardStats,
  AutopilotAlert,
  NotificationConfig,
} from './types';

// =============================================================================
// Mock Market Signals
// =============================================================================

export const mockMarketSignals: MarketSignal[] = [
  {
    id: 'sig-mkt-001',
    source: 'market_data',
    signal_type: 'interest_rate_change',
    signal_strength: 'strong',
    timestamp: '2024-12-08T08:00:00Z',
    data_point: 'Fed Funds Rate',
    value: 5.5,
    change_percentage: 0.25,
    direction: 'negative',
    impact_on_covenant: 'Interest coverage ratios may tighten as debt service costs increase',
    confidence: 92,
    description: 'Federal Reserve raised interest rates by 25bps, increasing borrowing costs across portfolios',
    source_url: 'https://federalreserve.gov',
  },
  {
    id: 'sig-mkt-002',
    source: 'market_data',
    signal_type: 'sector_index_change',
    signal_strength: 'moderate',
    timestamp: '2024-12-07T16:00:00Z',
    data_point: 'Manufacturing PMI',
    value: 47.2,
    change_percentage: -3.5,
    direction: 'negative',
    impact_on_covenant: 'Manufacturing sector contraction signals potential revenue pressure',
    confidence: 85,
    description: 'Manufacturing PMI dropped below 50, indicating sector contraction',
  },
  {
    id: 'sig-mkt-003',
    source: 'macro_indicators',
    signal_type: 'gdp_forecast',
    signal_strength: 'moderate',
    timestamp: '2024-12-06T10:00:00Z',
    data_point: 'Q1 2025 GDP Forecast',
    value: 1.8,
    change_percentage: -0.7,
    direction: 'negative',
    impact_on_covenant: 'Slower economic growth may impact borrower revenue and EBITDA',
    confidence: 78,
    description: 'Economic forecasters revised Q1 2025 GDP growth downward',
  },
  {
    id: 'sig-mkt-004',
    source: 'market_data',
    signal_type: 'credit_spread',
    signal_strength: 'strong',
    timestamp: '2024-12-08T09:30:00Z',
    data_point: 'BB Credit Spread',
    value: 385,
    change_percentage: 45,
    direction: 'negative',
    impact_on_covenant: 'Widening spreads indicate market stress and refinancing risk',
    confidence: 88,
    description: 'High yield credit spreads widened significantly, signaling risk-off sentiment',
  },
];

// =============================================================================
// Mock Transaction Pattern Signals
// =============================================================================

export const mockTransactionPatterns: TransactionPatternSignal[] = [
  {
    id: 'sig-txn-001',
    borrower_id: '1',
    borrower_name: 'ABC Holdings LLC',
    facility_id: '1',
    pattern_type: 'cash_flow',
    pattern_description: 'Operating cash flow showing consistent quarterly improvement',
    trend_direction: 'improving',
    trend_velocity: 8.5,
    trend_acceleration: 2.1,
    impact_on_covenants: ['Leverage Ratio', 'Fixed Charge Coverage'],
    risk_contribution: 15,
    historical_values: [
      { period: 'Q1 2024', value: 42.5 },
      { period: 'Q2 2024', value: 45.8 },
      { period: 'Q3 2024', value: 49.2 },
      { period: 'Q4 2024', value: 52.1 },
    ],
    detected_at: '2024-12-08T00:00:00Z',
    data_freshness: 'daily',
  },
  {
    id: 'sig-txn-002',
    borrower_id: '2',
    borrower_name: 'XYZ Corporation',
    facility_id: '2',
    pattern_type: 'receivables',
    pattern_description: 'Days sales outstanding increasing, signaling collection issues',
    trend_direction: 'declining',
    trend_velocity: -12.3,
    trend_acceleration: -3.5,
    impact_on_covenants: ['Leverage Ratio', 'Working Capital'],
    risk_contribution: 35,
    historical_values: [
      { period: 'Q1 2024', value: 45 },
      { period: 'Q2 2024', value: 52 },
      { period: 'Q3 2024', value: 58 },
      { period: 'Q4 2024', value: 65 },
    ],
    detected_at: '2024-12-07T00:00:00Z',
    data_freshness: 'weekly',
  },
  {
    id: 'sig-txn-003',
    borrower_id: '3',
    borrower_name: 'Delta Manufacturing Co',
    facility_id: '3',
    pattern_type: 'debt_service',
    pattern_description: 'Debt service coverage declining as interest costs rise',
    trend_direction: 'declining',
    trend_velocity: -18.2,
    trend_acceleration: -5.8,
    impact_on_covenants: ['Fixed Charge Coverage', 'Interest Coverage'],
    risk_contribution: 55,
    historical_values: [
      { period: 'Q1 2024', value: 1.35 },
      { period: 'Q2 2024', value: 1.25 },
      { period: 'Q3 2024', value: 1.15 },
      { period: 'Q4 2024', value: 1.05 },
    ],
    detected_at: '2024-12-08T00:00:00Z',
    data_freshness: 'daily',
  },
];

// =============================================================================
// Mock News Sentiment Signals
// =============================================================================

export const mockNewsSentiment: NewsSentimentSignal[] = [
  {
    id: 'sig-news-001',
    borrower_id: '3',
    sentiment_score: -0.72,
    sentiment_label: 'negative',
    confidence: 88,
    article_title: 'Delta Manufacturing Faces Supply Chain Headwinds',
    article_summary: 'Delta Manufacturing Co reported ongoing supply chain disruptions affecting Q4 production targets, potentially impacting full-year financial performance.',
    source_name: 'Manufacturing Weekly',
    published_at: '2024-12-07T14:30:00Z',
    entities_mentioned: ['Delta Manufacturing Co', 'Supply Chain'],
    topics: ['supply_chain', 'production', 'manufacturing'],
    credit_relevance: 78,
    potential_covenant_impact: 'May affect EBITDA and leverage covenant compliance',
  },
  {
    id: 'sig-news-002',
    industry: 'manufacturing',
    sentiment_score: -0.45,
    sentiment_label: 'negative',
    confidence: 82,
    article_title: 'Manufacturing Sector Braces for Economic Slowdown',
    article_summary: 'Industry analysts predict challenging conditions for manufacturing sector in 2025 as consumer demand weakens and input costs remain elevated.',
    source_name: 'Industry Insights',
    published_at: '2024-12-06T09:15:00Z',
    entities_mentioned: ['Manufacturing Sector'],
    topics: ['economic_outlook', 'manufacturing', 'demand'],
    credit_relevance: 65,
    potential_covenant_impact: 'Sector-wide pressure may affect multiple borrowers',
  },
  {
    id: 'sig-news-003',
    borrower_id: '1',
    sentiment_score: 0.65,
    sentiment_label: 'positive',
    confidence: 85,
    article_title: 'ABC Holdings Reports Strong Q4 Performance',
    article_summary: 'ABC Holdings LLC exceeded analyst expectations with robust Q4 results, driven by operational improvements and cost management initiatives.',
    source_name: 'Business Wire',
    published_at: '2024-12-05T16:00:00Z',
    entities_mentioned: ['ABC Holdings LLC'],
    topics: ['earnings', 'performance', 'growth'],
    credit_relevance: 90,
    potential_covenant_impact: 'Positive for covenant compliance and headroom maintenance',
  },
];

// =============================================================================
// Mock Benchmark Signals
// =============================================================================

export const mockBenchmarkSignals: BenchmarkSignal[] = [
  {
    id: 'sig-bench-001',
    industry: 'manufacturing',
    covenant_type: 'leverage_ratio',
    current_median: 4.0,
    previous_median: 4.2,
    change_percentage: -4.8,
    borrower_position: 'at_median',
    percentile_rank: 52,
    market_trend: 'tightening',
    requires_attention: true,
    attention_reason: 'Market thresholds tightening while borrower headroom declining',
  },
  {
    id: 'sig-bench-002',
    industry: 'technology',
    covenant_type: 'leverage_ratio',
    current_median: 3.25,
    previous_median: 3.5,
    change_percentage: -7.1,
    borrower_position: 'below_median',
    percentile_rank: 28,
    market_trend: 'tightening',
    requires_attention: true,
    attention_reason: 'Borrower leverage tighter than market but declining headroom',
  },
  {
    id: 'sig-bench-003',
    industry: 'manufacturing',
    covenant_type: 'fixed_charge_coverage',
    current_median: 1.2,
    previous_median: 1.15,
    change_percentage: 4.3,
    borrower_position: 'below_median',
    percentile_rank: 35,
    market_trend: 'loosening',
    requires_attention: false,
  },
];

// =============================================================================
// Mock Autopilot Predictions
// =============================================================================

export const mockAutopilotPredictions: AutopilotBreachPrediction[] = [
  {
    id: 'pred-001',
    covenant_id: '3',
    covenant_name: 'Leverage Ratio',
    facility_id: '2',
    facility_name: 'XYZ Corp Revolver',
    borrower_id: '2',
    borrower_name: 'XYZ Corporation',
    prediction_date: '2024-12-08',
    prediction_horizon_months: 12,
    breach_probability_6m: 35,
    breach_probability_9m: 52,
    breach_probability_12m: 68,
    overall_risk_level: 'high',
    confidence_score: 82,
    projected_breach_date: '2025-09-30',
    projected_breach_quarter: 'Q3 2025',
    days_until_projected_breach: 296,
    contributing_signals: [
      {
        signal_source: 'transaction_patterns',
        signal_id: 'sig-txn-002',
        signal_summary: 'Receivables collection deteriorating - DSO increased 44% YoY',
        impact: 'negative',
        weight: 35,
        confidence: 88,
        data_freshness: 'weekly',
        last_updated: '2024-12-07T00:00:00Z',
      },
      {
        signal_source: 'market_data',
        signal_id: 'sig-mkt-001',
        signal_summary: 'Rising interest rates increasing debt service burden',
        impact: 'negative',
        weight: 25,
        confidence: 92,
        data_freshness: 'real-time',
        last_updated: '2024-12-08T08:00:00Z',
      },
      {
        signal_source: 'industry_benchmarks',
        signal_id: 'sig-bench-002',
        signal_summary: 'Technology sector covenants tightening 7.1% YoY',
        impact: 'negative',
        weight: 20,
        confidence: 85,
        data_freshness: 'monthly',
        last_updated: '2024-12-01T00:00:00Z',
      },
      {
        signal_source: 'historical_trends',
        signal_id: 'hist-001',
        signal_summary: 'Consistent quarterly deterioration in headroom',
        impact: 'negative',
        weight: 20,
        confidence: 90,
        data_freshness: 'quarterly',
        last_updated: '2024-09-30T00:00:00Z',
      },
    ],
    signal_correlation_score: 0.78,
    quarterly_projections: [
      {
        quarter: 'Q1 2025',
        projected_ratio: 3.2,
        breach_probability: 25,
        confidence: 85,
        key_drivers: ['Continued receivables pressure', 'Seasonal revenue dip'],
        optimistic_ratio: 3.0,
        pessimistic_ratio: 3.35,
      },
      {
        quarter: 'Q2 2025',
        projected_ratio: 3.35,
        breach_probability: 42,
        confidence: 78,
        key_drivers: ['Working capital strain', 'Interest cost escalation'],
        optimistic_ratio: 3.15,
        pessimistic_ratio: 3.5,
      },
      {
        quarter: 'Q3 2025',
        projected_ratio: 3.48,
        breach_probability: 68,
        confidence: 72,
        key_drivers: ['Cumulative headroom erosion', 'Market conditions'],
        optimistic_ratio: 3.3,
        pessimistic_ratio: 3.65,
      },
    ],
    leading_indicators: [
      {
        indicator_name: 'Days Sales Outstanding',
        indicator_type: 'transaction_patterns',
        current_value: 65,
        threshold_value: 50,
        status: 'warning',
        trend: 'deteriorating',
        lead_time_months: 6,
        historical_accuracy: 78,
        description: 'Collection efficiency declining, typically precedes leverage deterioration by 2 quarters',
      },
      {
        indicator_name: 'Working Capital Ratio',
        indicator_type: 'transaction_patterns',
        current_value: 1.15,
        threshold_value: 1.25,
        status: 'warning',
        trend: 'deteriorating',
        lead_time_months: 4,
        historical_accuracy: 82,
        description: 'Working capital pressure building, often leads to covenant stress',
      },
      {
        indicator_name: 'Interest Rate Exposure',
        indicator_type: 'market_data',
        current_value: 72,
        threshold_value: 60,
        status: 'critical',
        trend: 'deteriorating',
        lead_time_months: 3,
        historical_accuracy: 85,
        description: 'High floating rate exposure in rising rate environment',
      },
    ],
    root_causes: [
      {
        cause_type: 'Working Capital Management',
        description: 'Receivables collection efficiency has deteriorated significantly, extending the cash conversion cycle',
        contribution_percentage: 40,
        addressable: true,
        recommended_action: 'Implement enhanced collection procedures and consider factoring arrangement',
        confidence: 85,
      },
      {
        cause_type: 'Interest Rate Sensitivity',
        description: 'High proportion of floating rate debt amplifying impact of Fed rate increases',
        contribution_percentage: 30,
        addressable: true,
        recommended_action: 'Consider interest rate hedging to cap exposure',
        confidence: 90,
      },
      {
        cause_type: 'Market Conditions',
        description: 'Technology sector facing headwinds with customer spending deferrals',
        contribution_percentage: 20,
        addressable: false,
        confidence: 75,
      },
      {
        cause_type: 'Competitive Pressure',
        description: 'Margin compression from increased competition in core markets',
        contribution_percentage: 10,
        addressable: true,
        recommended_action: 'Review pricing strategy and cost structure',
        confidence: 70,
      },
    ],
    summary: 'XYZ Corporation faces elevated breach risk within 12 months driven by deteriorating working capital efficiency and rising interest costs. Multiple leading indicators are flashing warning signals, with 78% correlation across signal sources. Proactive intervention recommended.',
    key_risks: [
      'Receivables collection continues to deteriorate',
      'Further interest rate increases by Federal Reserve',
      'Customer spending pullback accelerates',
      'Working capital strain triggers liquidity issues',
    ],
    immediate_actions: [
      'Schedule meeting with borrower management to discuss working capital trends',
      'Request updated 12-month cash flow projections',
      'Review interest rate hedging options with borrower',
      'Begin preliminary covenant amendment discussions',
    ],
    generated_at: '2024-12-08T06:00:00Z',
    model_version: 'autopilot-v2.1',
    data_sources_used: ['market_data', 'transaction_patterns', 'industry_benchmarks', 'historical_trends', 'news_sentiment'],
  },
  {
    id: 'pred-002',
    covenant_id: '4',
    covenant_name: 'Fixed Charge Coverage',
    facility_id: '3',
    facility_name: 'Delta Manufacturing TL',
    borrower_id: '3',
    borrower_name: 'Delta Manufacturing Co',
    prediction_date: '2024-12-08',
    prediction_horizon_months: 12,
    breach_probability_6m: 88,
    breach_probability_9m: 82,
    breach_probability_12m: 75,
    overall_risk_level: 'critical',
    confidence_score: 92,
    projected_breach_date: '2025-03-31',
    projected_breach_quarter: 'Q1 2025',
    days_until_projected_breach: 113,
    contributing_signals: [
      {
        signal_source: 'transaction_patterns',
        signal_id: 'sig-txn-003',
        signal_summary: 'Debt service coverage in accelerating decline',
        impact: 'negative',
        weight: 40,
        confidence: 95,
        data_freshness: 'daily',
        last_updated: '2024-12-08T00:00:00Z',
      },
      {
        signal_source: 'news_sentiment',
        signal_id: 'sig-news-001',
        signal_summary: 'Negative press coverage on supply chain issues',
        impact: 'negative',
        weight: 20,
        confidence: 88,
        data_freshness: 'daily',
        last_updated: '2024-12-07T14:30:00Z',
      },
      {
        signal_source: 'market_data',
        signal_id: 'sig-mkt-002',
        signal_summary: 'Manufacturing sector PMI in contraction territory',
        impact: 'negative',
        weight: 25,
        confidence: 85,
        data_freshness: 'weekly',
        last_updated: '2024-12-07T16:00:00Z',
      },
      {
        signal_source: 'historical_trends',
        signal_id: 'hist-002',
        signal_summary: 'Four consecutive quarters of FCCR decline',
        impact: 'negative',
        weight: 15,
        confidence: 98,
        data_freshness: 'quarterly',
        last_updated: '2024-09-30T00:00:00Z',
      },
    ],
    signal_correlation_score: 0.92,
    quarterly_projections: [
      {
        quarter: 'Q1 2025',
        projected_ratio: 0.98,
        breach_probability: 88,
        confidence: 90,
        key_drivers: ['Waiver expiration', 'Continued EBITDA pressure'],
        optimistic_ratio: 1.05,
        pessimistic_ratio: 0.92,
      },
      {
        quarter: 'Q2 2025',
        projected_ratio: 1.02,
        breach_probability: 82,
        confidence: 82,
        key_drivers: ['Seasonal uptick', 'Cost reduction initiatives'],
        optimistic_ratio: 1.12,
        pessimistic_ratio: 0.95,
      },
      {
        quarter: 'Q3 2025',
        projected_ratio: 1.08,
        breach_probability: 75,
        confidence: 75,
        key_drivers: ['Peak season production', 'Restructuring benefits'],
        optimistic_ratio: 1.18,
        pessimistic_ratio: 1.0,
      },
    ],
    leading_indicators: [
      {
        indicator_name: 'EBITDA Margin',
        indicator_type: 'transaction_patterns',
        current_value: 8.2,
        threshold_value: 12.0,
        status: 'critical',
        trend: 'deteriorating',
        lead_time_months: 3,
        historical_accuracy: 88,
        description: 'EBITDA margin compression directly impacts FCCR',
      },
      {
        indicator_name: 'Supply Chain Disruption Index',
        indicator_type: 'news_sentiment',
        current_value: 72,
        threshold_value: 50,
        status: 'critical',
        trend: 'deteriorating',
        lead_time_months: 4,
        historical_accuracy: 72,
        description: 'Supply chain issues affecting production and costs',
      },
      {
        indicator_name: 'Manufacturing PMI',
        indicator_type: 'market_data',
        current_value: 47.2,
        threshold_value: 50.0,
        status: 'warning',
        trend: 'stable',
        lead_time_months: 2,
        historical_accuracy: 80,
        description: 'Sector contraction weighing on performance',
      },
    ],
    root_causes: [
      {
        cause_type: 'Margin Compression',
        description: 'Input cost inflation not fully passed through to customers, compressing EBITDA margins',
        contribution_percentage: 45,
        addressable: true,
        recommended_action: 'Implement pricing increases and cost reduction program',
        confidence: 90,
      },
      {
        cause_type: 'Supply Chain Disruption',
        description: 'Ongoing supply chain issues causing production inefficiencies and higher costs',
        contribution_percentage: 30,
        addressable: true,
        recommended_action: 'Diversify supplier base and increase inventory buffers',
        confidence: 85,
      },
      {
        cause_type: 'Fixed Cost Base',
        description: 'High fixed cost structure amplifies impact of revenue fluctuations',
        contribution_percentage: 15,
        addressable: true,
        recommended_action: 'Evaluate opportunities to variabilize fixed costs',
        confidence: 80,
      },
      {
        cause_type: 'Sector Headwinds',
        description: 'Manufacturing sector broadly challenged by economic conditions',
        contribution_percentage: 10,
        addressable: false,
        confidence: 75,
      },
    ],
    summary: 'CRITICAL: Delta Manufacturing faces imminent breach when current waiver expires Q1 2025. Multi-signal analysis shows 92% correlation indicating high confidence prediction. Without intervention, FCCR projected to remain below 1.2x threshold through 2025. Immediate workout engagement required.',
    key_risks: [
      'Waiver expires Q1 2025 with no automatic extension',
      'EBITDA deterioration continuing at accelerating rate',
      'Supply chain issues persisting into 2025',
      'Sector-wide headwinds provide no near-term relief',
    ],
    immediate_actions: [
      'URGENT: Initiate waiver extension negotiations immediately',
      'Engage restructuring advisors to evaluate options',
      'Request detailed operational improvement plan from management',
      'Evaluate collateral position and recovery scenarios',
      'Prepare credit committee memo on restructuring options',
    ],
    generated_at: '2024-12-08T06:00:00Z',
    model_version: 'autopilot-v2.1',
    data_sources_used: ['market_data', 'transaction_patterns', 'industry_benchmarks', 'historical_trends', 'news_sentiment'],
  },
  {
    id: 'pred-003',
    covenant_id: '1',
    covenant_name: 'Leverage Ratio',
    facility_id: '1',
    facility_name: 'ABC Holdings - Term Loan A',
    borrower_id: '1',
    borrower_name: 'ABC Holdings LLC',
    prediction_date: '2024-12-08',
    prediction_horizon_months: 12,
    breach_probability_6m: 5,
    breach_probability_9m: 8,
    breach_probability_12m: 12,
    overall_risk_level: 'low',
    confidence_score: 88,
    projected_breach_date: null,
    projected_breach_quarter: null,
    days_until_projected_breach: null,
    contributing_signals: [
      {
        signal_source: 'transaction_patterns',
        signal_id: 'sig-txn-001',
        signal_summary: 'Operating cash flow improving 8.5% QoQ',
        impact: 'positive',
        weight: 40,
        confidence: 90,
        data_freshness: 'daily',
        last_updated: '2024-12-08T00:00:00Z',
      },
      {
        signal_source: 'news_sentiment',
        signal_id: 'sig-news-003',
        signal_summary: 'Positive press on Q4 performance',
        impact: 'positive',
        weight: 20,
        confidence: 85,
        data_freshness: 'daily',
        last_updated: '2024-12-05T16:00:00Z',
      },
      {
        signal_source: 'historical_trends',
        signal_id: 'hist-003',
        signal_summary: 'Four consecutive quarters of headroom improvement',
        impact: 'positive',
        weight: 30,
        confidence: 95,
        data_freshness: 'quarterly',
        last_updated: '2024-09-30T00:00:00Z',
      },
      {
        signal_source: 'industry_benchmarks',
        signal_id: 'sig-bench-001',
        signal_summary: 'Covenant at market median despite sector tightening',
        impact: 'neutral',
        weight: 10,
        confidence: 85,
        data_freshness: 'monthly',
        last_updated: '2024-12-01T00:00:00Z',
      },
    ],
    signal_correlation_score: 0.85,
    quarterly_projections: [
      {
        quarter: 'Q1 2025',
        projected_ratio: 3.1,
        breach_probability: 3,
        confidence: 90,
        key_drivers: ['Continued operational improvement', 'Stable market conditions'],
        optimistic_ratio: 2.9,
        pessimistic_ratio: 3.25,
      },
      {
        quarter: 'Q2 2025',
        projected_ratio: 3.0,
        breach_probability: 5,
        confidence: 85,
        key_drivers: ['Revenue growth', 'Cost management'],
        optimistic_ratio: 2.85,
        pessimistic_ratio: 3.2,
      },
      {
        quarter: 'Q3 2025',
        projected_ratio: 2.9,
        breach_probability: 8,
        confidence: 78,
        key_drivers: ['Strong cash generation', 'Debt paydown'],
        optimistic_ratio: 2.75,
        pessimistic_ratio: 3.1,
      },
    ],
    leading_indicators: [
      {
        indicator_name: 'Operating Cash Flow Trend',
        indicator_type: 'transaction_patterns',
        current_value: 8.5,
        threshold_value: 0,
        status: 'normal',
        trend: 'improving',
        lead_time_months: 4,
        historical_accuracy: 82,
        description: 'Positive cash flow trend supports covenant compliance',
      },
      {
        indicator_name: 'Revenue Growth Rate',
        indicator_type: 'transaction_patterns',
        current_value: 6.2,
        threshold_value: 3.0,
        status: 'normal',
        trend: 'stable',
        lead_time_months: 3,
        historical_accuracy: 78,
        description: 'Above-trend revenue growth maintaining headroom',
      },
    ],
    root_causes: [],
    summary: 'ABC Holdings maintains strong covenant compliance with improving trajectory. All leading indicators positive and 85% signal correlation supports low breach risk assessment. No immediate concerns identified.',
    key_risks: [
      'Macro economic deterioration could impact performance',
      'Unexpected operational issues',
    ],
    immediate_actions: [
      'Continue standard monitoring procedures',
      'No specific actions required',
    ],
    generated_at: '2024-12-08T06:00:00Z',
    model_version: 'autopilot-v2.1',
    data_sources_used: ['market_data', 'transaction_patterns', 'industry_benchmarks', 'historical_trends', 'news_sentiment'],
  },
];

// =============================================================================
// Mock Remediation Strategies
// =============================================================================

export const mockRemediationStrategies: RemediationStrategy[] = [
  {
    id: 'rem-001',
    prediction_id: 'pred-001',
    covenant_id: '3',
    strategy_type: 'operational_improvement',
    strategy_title: 'Working Capital Optimization Program',
    strategy_description: 'Implement comprehensive working capital management program focused on accelerating receivables collection and optimizing inventory levels to improve cash flow and reduce leverage.',
    estimated_effectiveness: 72,
    implementation_difficulty: 'medium',
    time_to_implement: '3-6 months',
    projected_headroom_improvement: 8.5,
    projected_breach_probability_reduction: 25,
    implementation_steps: [
      {
        step_number: 1,
        title: 'Receivables Assessment',
        description: 'Conduct detailed analysis of aging receivables and identify collection bottlenecks',
        responsible_party: 'CFO / Controller',
        due_date: '2025-01-15',
        status: 'pending',
        dependencies: [],
        documents_required: ['Aging Report', 'Customer Payment History'],
      },
      {
        step_number: 2,
        title: 'Collection Process Enhancement',
        description: 'Implement enhanced collection procedures including earlier follow-up and payment incentives',
        responsible_party: 'Accounts Receivable Manager',
        due_date: '2025-02-01',
        status: 'pending',
        dependencies: [1],
        documents_required: ['New Collection Policy'],
      },
      {
        step_number: 3,
        title: 'Inventory Optimization',
        description: 'Review inventory levels and implement demand-based ordering to reduce working capital tied up in stock',
        responsible_party: 'Operations Manager',
        due_date: '2025-03-01',
        status: 'pending',
        dependencies: [],
        documents_required: ['Inventory Analysis'],
      },
      {
        step_number: 4,
        title: 'Cash Flow Monitoring',
        description: 'Establish weekly cash flow monitoring dashboard and reporting',
        responsible_party: 'Finance Team',
        due_date: '2025-02-15',
        status: 'pending',
        dependencies: [1, 2],
        documents_required: ['Dashboard Specifications'],
      },
    ],
    required_approvals: ['CFO', 'CEO'],
    key_stakeholders: ['Management Team', 'Lender Group', 'Board of Directors'],
    implementation_risks: [
      'Customer pushback on accelerated collection',
      'Inventory optimization may cause short-term stockouts',
      'Requires management bandwidth during implementation',
    ],
    estimated_cost: {
      currency: 'USD',
      direct_costs: 150000,
      indirect_costs: 75000,
      total_estimated_cost: 225000,
      cost_breakdown: [
        { category: 'Consultant Fees', amount: 100000, description: 'Working capital optimization consultants' },
        { category: 'System Enhancements', amount: 50000, description: 'ERP system modifications' },
        { category: 'Training', amount: 25000, description: 'Staff training on new procedures' },
        { category: 'Internal Resources', amount: 50000, description: 'Management time allocation' },
      ],
      confidence_level: 'medium',
    },
    priority: 'high',
    recommended_start_date: '2025-01-02',
    status: 'pending',
    generated_at: '2024-12-08T06:00:00Z',
  },
  {
    id: 'rem-002',
    prediction_id: 'pred-001',
    covenant_id: '3',
    strategy_type: 'covenant_amendment',
    strategy_title: 'Proactive Covenant Amendment',
    strategy_description: 'Negotiate covenant amendment to increase leverage threshold from 3.5x to 4.0x, aligned with current market benchmarks and borrower trajectory.',
    estimated_effectiveness: 85,
    implementation_difficulty: 'medium',
    time_to_implement: '6-8 weeks',
    projected_headroom_improvement: 14.3,
    projected_breach_probability_reduction: 45,
    implementation_steps: [
      {
        step_number: 1,
        title: 'Amendment Request Preparation',
        description: 'Prepare formal amendment request with supporting financial analysis and market benchmarking',
        responsible_party: 'Relationship Manager',
        due_date: '2025-01-10',
        status: 'pending',
        dependencies: [],
        documents_required: ['Amendment Request Letter', 'Financial Projections', 'Market Benchmark Analysis'],
      },
      {
        step_number: 2,
        title: 'Lender Outreach',
        description: 'Initial discussions with agent bank and key lenders to gauge appetite for amendment',
        responsible_party: 'Relationship Manager',
        due_date: '2025-01-20',
        status: 'pending',
        dependencies: [1],
        documents_required: ['Lender Presentation'],
      },
      {
        step_number: 3,
        title: 'Term Negotiation',
        description: 'Negotiate specific amendment terms including new threshold and any pricing adjustments',
        responsible_party: 'Senior Relationship Manager',
        due_date: '2025-02-10',
        status: 'pending',
        dependencies: [2],
        documents_required: ['Term Sheet'],
      },
      {
        step_number: 4,
        title: 'Documentation and Execution',
        description: 'Finalize amendment documentation and obtain required signatures',
        responsible_party: 'Legal Counsel',
        due_date: '2025-02-28',
        status: 'pending',
        dependencies: [3],
        documents_required: ['Amendment Agreement', 'Board Resolutions'],
      },
    ],
    required_approvals: ['Credit Committee', 'Agent Bank', 'Required Lenders'],
    key_stakeholders: ['Borrower Management', 'Agent Bank', 'Syndicate Lenders', 'Legal Counsel'],
    implementation_risks: [
      'Lenders may require pricing increase',
      'May require additional collateral or guarantees',
      'Potential reputational impact with lenders',
    ],
    estimated_cost: {
      currency: 'USD',
      direct_costs: 85000,
      indirect_costs: 35000,
      total_estimated_cost: 120000,
      cost_breakdown: [
        { category: 'Amendment Fee', amount: 50000, description: 'Standard amendment fee to lenders' },
        { category: 'Legal Fees', amount: 35000, description: 'External counsel fees' },
        { category: 'Internal Resources', amount: 35000, description: 'Staff time for negotiation and documentation' },
      ],
      confidence_level: 'high',
    },
    priority: 'high',
    recommended_start_date: '2025-01-02',
    status: 'pending',
    generated_at: '2024-12-08T06:00:00Z',
  },
  {
    id: 'rem-003',
    prediction_id: 'pred-002',
    covenant_id: '4',
    strategy_type: 'waiver_request',
    strategy_title: 'Waiver Extension with Performance Milestones',
    strategy_description: 'Negotiate 12-month waiver extension for FCCR covenant with quarterly performance milestones and enhanced reporting requirements.',
    estimated_effectiveness: 78,
    implementation_difficulty: 'high',
    time_to_implement: '4-6 weeks',
    projected_headroom_improvement: 0,
    projected_breach_probability_reduction: 88,
    implementation_steps: [
      {
        step_number: 1,
        title: 'Waiver Request Package',
        description: 'Prepare comprehensive waiver extension request with detailed turnaround plan',
        responsible_party: 'Workout Officer',
        due_date: '2025-01-05',
        status: 'pending',
        dependencies: [],
        documents_required: ['Waiver Request', 'Turnaround Plan', 'Cash Flow Projections'],
      },
      {
        step_number: 2,
        title: 'Management Meeting',
        description: 'Conduct in-person meeting with borrower management to discuss turnaround plan',
        responsible_party: 'Senior Workout Officer',
        due_date: '2025-01-12',
        status: 'pending',
        dependencies: [1],
        documents_required: ['Management Presentation'],
      },
      {
        step_number: 3,
        title: 'Credit Committee Approval',
        description: 'Present waiver request to credit committee for approval',
        responsible_party: 'Workout Officer',
        due_date: '2025-01-25',
        status: 'pending',
        dependencies: [2],
        documents_required: ['Credit Committee Memo'],
      },
      {
        step_number: 4,
        title: 'Lender Consent',
        description: 'Obtain required lender consents for waiver extension',
        responsible_party: 'Agent Bank',
        due_date: '2025-02-10',
        status: 'pending',
        dependencies: [3],
        documents_required: ['Consent Request', 'Waiver Letter'],
      },
    ],
    required_approvals: ['Credit Committee', 'Required Lenders (66.67%)', 'Board of Directors'],
    key_stakeholders: ['Borrower Management', 'Workout Team', 'Agent Bank', 'Syndicate Lenders', 'Legal Counsel'],
    implementation_risks: [
      'Lenders may demand more stringent terms',
      'May require additional security or guarantees',
      'Borrower may not achieve performance milestones',
      'Could trigger default on other agreements',
    ],
    estimated_cost: {
      currency: 'USD',
      direct_costs: 175000,
      indirect_costs: 50000,
      total_estimated_cost: 225000,
      cost_breakdown: [
        { category: 'Waiver Fee', amount: 100000, description: 'Fee to lenders for waiver extension' },
        { category: 'Legal Fees', amount: 50000, description: 'External counsel fees' },
        { category: 'Advisor Fees', amount: 25000, description: 'Financial advisor fees' },
        { category: 'Internal Resources', amount: 50000, description: 'Workout team time allocation' },
      ],
      confidence_level: 'medium',
    },
    priority: 'critical',
    recommended_start_date: '2024-12-15',
    status: 'in_progress',
    generated_at: '2024-12-08T06:00:00Z',
  },
];

// =============================================================================
// Mock Dashboard Stats
// =============================================================================

export const mockAutopilotDashboardStats: AutopilotDashboardStats = {
  as_of_date: '2024-12-08T06:00:00Z',
  total_predictions_active: 156,
  predictions_by_risk_level: {
    low: 98,
    medium: 35,
    high: 18,
    critical: 5,
  },
  total_signals_processed: 12847,
  signals_by_source: {
    market_data: 3245,
    transaction_patterns: 4521,
    news_sentiment: 1823,
    industry_benchmarks: 1456,
    historical_trends: 987,
    seasonal_patterns: 423,
    peer_comparison: 312,
    macro_indicators: 80,
  },
  new_signals_24h: 342,
  projected_breaches_6m: 12,
  projected_breaches_12m: 23,
  average_days_to_breach: 186,
  active_remediations: 8,
  remediations_completed_30d: 5,
  remediation_success_rate: 78,
  notifications_sent_24h: 23,
  notifications_pending: 5,
  covenants_monitored: 456,
  facilities_monitored: 128,
  data_coverage_percentage: 94.5,
  prediction_accuracy_6m: 82,
  prediction_accuracy_12m: 76,
  model_confidence_average: 81,
};

// =============================================================================
// Mock Alerts
// =============================================================================

export const mockAutopilotAlerts: AutopilotAlert[] = [
  {
    id: 'alert-ap-001',
    alert_type: 'breach_imminent',
    priority: 'critical',
    title: 'CRITICAL: Delta Manufacturing Breach Imminent',
    message: 'Fixed Charge Coverage covenant projected to breach in 113 days when current waiver expires. Immediate action required.',
    prediction_id: 'pred-002',
    covenant_id: '4',
    facility_id: '3',
    borrower_name: 'Delta Manufacturing Co',
    suggested_actions: [
      'Initiate waiver extension negotiations',
      'Schedule management meeting',
      'Prepare credit committee memo',
    ],
    created_at: '2024-12-08T06:00:00Z',
    acknowledged: false,
  },
  {
    id: 'alert-ap-002',
    alert_type: 'risk_escalation',
    priority: 'high',
    title: 'Risk Escalation: XYZ Corp Leverage',
    message: 'Leverage ratio breach probability increased from 42% to 68% over 12-month horizon. Multiple negative signals detected.',
    prediction_id: 'pred-001',
    covenant_id: '3',
    facility_id: '2',
    borrower_name: 'XYZ Corporation',
    suggested_actions: [
      'Review working capital trends with borrower',
      'Consider proactive covenant amendment',
      'Request updated projections',
    ],
    created_at: '2024-12-08T04:00:00Z',
    acknowledged: false,
  },
  {
    id: 'alert-ap-003',
    alert_type: 'new_signal',
    priority: 'medium',
    title: 'New Signal: Interest Rate Increase',
    message: 'Federal Reserve raised rates 25bps. Analyzing impact across portfolio - 12 facilities with significant floating rate exposure.',
    suggested_actions: [
      'Review interest coverage ratios for affected facilities',
      'Assess hedging status',
    ],
    created_at: '2024-12-08T08:00:00Z',
    acknowledged: true,
    acknowledged_at: '2024-12-08T08:15:00Z',
    acknowledged_by: 'john.smith@bank.com',
  },
  {
    id: 'alert-ap-004',
    alert_type: 'remediation_due',
    priority: 'high',
    title: 'Remediation Step Due: Working Capital Assessment',
    message: 'Working capital assessment for XYZ Corporation due in 7 days. Step 1 of 4 in Working Capital Optimization Program.',
    prediction_id: 'pred-001',
    covenant_id: '3',
    facility_id: '2',
    borrower_name: 'XYZ Corporation',
    suggested_actions: [
      'Follow up with CFO on aging report',
      'Schedule assessment review meeting',
    ],
    created_at: '2024-12-07T09:00:00Z',
    acknowledged: false,
  },
];

// =============================================================================
// Mock Notification Config
// =============================================================================

export const mockNotificationConfigs: NotificationConfig[] = [
  {
    id: 'config-001',
    user_id: 'user-001',
    trigger_risk_level: 'high',
    trigger_probability_threshold: 50,
    trigger_days_before_breach: 180,
    enabled_channels: ['email', 'in_app'],
    email_recipients: ['credit.manager@bank.com', 'risk.officer@bank.com'],
    sms_recipients: [],
    webhook_urls: [],
    max_notifications_per_day: 10,
    digest_enabled: true,
    digest_frequency: 'daily',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-12-01T00:00:00Z',
  },
];

// =============================================================================
// Helper Functions
// =============================================================================

export function getAutopilotPrediction(id: string): AutopilotBreachPrediction | undefined {
  return mockAutopilotPredictions.find(p => p.id === id);
}

export function getAutopilotPredictionByCovenant(covenantId: string): AutopilotBreachPrediction | undefined {
  return mockAutopilotPredictions.find(p => p.covenant_id === covenantId);
}

export function getRemediationStrategies(predictionId: string): RemediationStrategy[] {
  return mockRemediationStrategies.filter(r => r.prediction_id === predictionId);
}

export function getUnacknowledgedAlerts(): AutopilotAlert[] {
  return mockAutopilotAlerts.filter(a => !a.acknowledged);
}

export function getCriticalPredictions(): AutopilotBreachPrediction[] {
  return mockAutopilotPredictions.filter(p => p.overall_risk_level === 'critical');
}

export function getHighRiskPredictions(): AutopilotBreachPrediction[] {
  return mockAutopilotPredictions.filter(p => p.overall_risk_level === 'high' || p.overall_risk_level === 'critical');
}
