import type {
  PortfolioOptimizationSummary,
  PortfolioConcentration,
  SectorAllocation,
  LoanTypeAllocation,
  SyndicationOpportunity,
  DivestmentCandidate,
  MarketBenchmark,
  InstitutionalESGTarget,
  DiversificationOpportunity,
  PortfolioOptimizationScenario,
  OptimizationAction,
  ESGPortfolioScore,
} from './types';

export const mockPortfolioESGScore: ESGPortfolioScore = {
  overall_score: 72,
  environmental_score: 68,
  social_score: 75,
  governance_score: 74,
  methodology: 'LMA ESG Scoring Framework v2.0',
  last_updated: new Date().toISOString(),
  peer_comparison: {
    rank: 8,
    total_peers: 45,
    percentile: 82,
  },
};

export const mockConcentrationAnalysis: PortfolioConcentration[] = [
  {
    dimension: 'industry',
    name: 'Energy',
    exposure: 280000000,
    percentage: 32.9,
    limit_percentage: 25,
    status: 'exceeds_limit',
    facility_count: 4,
    avg_esg_score: 62,
  },
  {
    dimension: 'industry',
    name: 'Real Estate',
    exposure: 175000000,
    percentage: 20.6,
    limit_percentage: 25,
    status: 'within_limits',
    facility_count: 3,
    avg_esg_score: 78,
  },
  {
    dimension: 'industry',
    name: 'Manufacturing',
    exposure: 150000000,
    percentage: 17.6,
    limit_percentage: 20,
    status: 'approaching_limit',
    facility_count: 2,
    avg_esg_score: 71,
  },
  {
    dimension: 'loan_type',
    name: 'Sustainability-Linked',
    exposure: 350000000,
    percentage: 41.2,
    limit_percentage: 50,
    status: 'within_limits',
    facility_count: 5,
    avg_esg_score: 74,
  },
  {
    dimension: 'loan_type',
    name: 'Transition Loans',
    exposure: 200000000,
    percentage: 23.5,
    limit_percentage: 20,
    status: 'exceeds_limit',
    facility_count: 2,
    avg_esg_score: 58,
  },
  {
    dimension: 'borrower',
    name: 'Delta Energy Corp',
    exposure: 200000000,
    percentage: 23.5,
    limit_percentage: 15,
    status: 'exceeds_limit',
    facility_count: 1,
    avg_esg_score: 55,
  },
];

export const mockSectorAllocation: SectorAllocation[] = [
  {
    sector: 'energy',
    label: 'Energy',
    exposure: 280000000,
    percentage: 32.9,
    facility_count: 4,
    avg_esg_performance: 62,
    target_percentage: 25,
    variance: 7.9,
    risk_level: 'high',
  },
  {
    sector: 'real_estate',
    label: 'Real Estate',
    exposure: 175000000,
    percentage: 20.6,
    facility_count: 3,
    avg_esg_performance: 78,
    target_percentage: 20,
    variance: 0.6,
    risk_level: 'low',
  },
  {
    sector: 'manufacturing',
    label: 'Manufacturing',
    exposure: 150000000,
    percentage: 17.6,
    facility_count: 2,
    avg_esg_performance: 71,
    target_percentage: 15,
    variance: 2.6,
    risk_level: 'medium',
  },
  {
    sector: 'technology',
    label: 'Technology',
    exposure: 100000000,
    percentage: 11.8,
    facility_count: 2,
    avg_esg_performance: 82,
    target_percentage: 15,
    variance: -3.2,
    risk_level: 'low',
  },
  {
    sector: 'construction',
    label: 'Construction',
    exposure: 100000000,
    percentage: 11.8,
    facility_count: 2,
    avg_esg_performance: 68,
    target_percentage: 10,
    variance: 1.8,
    risk_level: 'medium',
  },
  {
    sector: 'healthcare',
    label: 'Healthcare',
    exposure: 45000000,
    percentage: 5.3,
    facility_count: 1,
    avg_esg_performance: 85,
    target_percentage: 15,
    variance: -9.7,
    risk_level: 'low',
  },
];

export const mockLoanTypeAllocation: LoanTypeAllocation[] = [
  {
    loan_type: 'sustainability_linked',
    exposure: 350000000,
    percentage: 41.2,
    facility_count: 5,
    avg_margin_bps: 195,
    target_percentage: 40,
    variance: 1.2,
  },
  {
    loan_type: 'green_loan',
    exposure: 175000000,
    percentage: 20.6,
    facility_count: 3,
    avg_margin_bps: 175,
    target_percentage: 25,
    variance: -4.4,
  },
  {
    loan_type: 'transition_loan',
    exposure: 200000000,
    percentage: 23.5,
    facility_count: 2,
    avg_margin_bps: 235,
    target_percentage: 15,
    variance: 8.5,
  },
  {
    loan_type: 'social_loan',
    exposure: 100000000,
    percentage: 11.8,
    facility_count: 2,
    avg_margin_bps: 185,
    target_percentage: 15,
    variance: -3.2,
  },
  {
    loan_type: 'esg_linked_hybrid',
    exposure: 25000000,
    percentage: 2.9,
    facility_count: 1,
    avg_margin_bps: 205,
    target_percentage: 5,
    variance: -2.1,
  },
];

export const mockSyndicationOpportunities: SyndicationOpportunity[] = [
  {
    id: 'synd-1',
    facility_name: 'Nordic Wind Holdings SLL',
    borrower_name: 'Nordic Wind Holdings AS',
    borrower_industry: 'energy',
    esg_loan_type: 'green_loan',
    total_facility_amount: 500000000,
    available_participation: 75000000,
    min_participation: 25000000,
    lead_arranger: 'Nordea',
    syndication_deadline: '2025-01-31',
    esg_rating: 'AA',
    esg_score: 85,
    margin_bps: 165,
    maturity_date: '2030-06-30',
    key_kpis: ['Renewable capacity additions', 'Carbon avoided', 'Community benefit'],
    framework_alignment: ['EU Taxonomy', 'LMA Green Loan Principles'],
    match_score: 92,
    recommendation_reason: 'High ESG score would improve portfolio average. Green loan allocation currently below target.',
  },
  {
    id: 'synd-2',
    facility_name: 'HealthTech Global SLL',
    borrower_name: 'HealthTech Global Inc',
    borrower_industry: 'healthcare',
    esg_loan_type: 'social_loan',
    total_facility_amount: 300000000,
    available_participation: 45000000,
    min_participation: 15000000,
    lead_arranger: 'JP Morgan',
    syndication_deadline: '2025-02-15',
    esg_rating: 'A+',
    esg_score: 81,
    margin_bps: 180,
    maturity_date: '2029-12-31',
    key_kpis: ['Healthcare access expansion', 'Affordability index', 'Patient outcomes'],
    framework_alignment: ['LMA Social Loan Principles', 'SDG 3'],
    match_score: 88,
    recommendation_reason: 'Healthcare sector underweight. Social loan category below target. Strong ESG credentials.',
  },
  {
    id: 'synd-3',
    facility_name: 'TechForward Sustainability Facility',
    borrower_name: 'TechForward Corp',
    borrower_industry: 'technology',
    esg_loan_type: 'sustainability_linked',
    total_facility_amount: 400000000,
    available_participation: 60000000,
    min_participation: 20000000,
    lead_arranger: 'Goldman Sachs',
    syndication_deadline: '2025-03-01',
    esg_rating: 'AA-',
    esg_score: 79,
    margin_bps: 155,
    maturity_date: '2030-03-31',
    key_kpis: ['Data center PUE', 'Renewable energy usage', 'E-waste recycling rate'],
    framework_alignment: ['SLLP', 'Science Based Targets'],
    match_score: 85,
    recommendation_reason: 'Technology sector offers diversification. Strong margin with sustainability upside.',
  },
  {
    id: 'synd-4',
    facility_name: 'CleanTransit Europe Green Bond',
    borrower_name: 'CleanTransit Holdings BV',
    borrower_industry: 'transportation',
    esg_loan_type: 'green_loan',
    total_facility_amount: 250000000,
    available_participation: 40000000,
    min_participation: 10000000,
    lead_arranger: 'BNP Paribas',
    syndication_deadline: '2025-01-20',
    esg_rating: 'A',
    esg_score: 76,
    margin_bps: 170,
    maturity_date: '2028-09-30',
    key_kpis: ['EV fleet conversion', 'Emissions reduction', 'Route efficiency'],
    framework_alignment: ['EU Taxonomy', 'LMA Green Loan Principles'],
    match_score: 78,
    recommendation_reason: 'Transportation sector adds diversification. Aligned with EU taxonomy for green transport.',
  },
];

export const mockDivestmentCandidates: DivestmentCandidate[] = [
  {
    id: 'divest-1',
    facility_id: '4',
    facility_name: 'Delta Transition Finance',
    borrower_name: 'Delta Energy Corp',
    borrower_industry: 'energy',
    esg_loan_type: 'transition_loan',
    current_exposure: 180000000,
    current_margin_bps: 240,
    esg_performance: 'off_track',
    esg_score: 45,
    reason: [
      'Off-track on 3 of 5 KPIs',
      'Single borrower concentration exceeds 15% limit',
      'Transition pathway credibility concerns',
      'Recent negative ESG news coverage',
    ],
    expected_market_price_pct: 97.5,
    portfolio_impact: {
      exposure_reduction: 180000000,
      esg_score_improvement: 4.2,
      concentration_improvement: 8.5,
    },
    priority: 'high',
  },
  {
    id: 'divest-2',
    facility_id: '7',
    facility_name: 'Legacy Mining Transition',
    borrower_name: 'Legacy Mining Corp',
    borrower_industry: 'energy',
    esg_loan_type: 'transition_loan',
    current_exposure: 85000000,
    current_margin_bps: 255,
    esg_performance: 'at_risk',
    esg_score: 52,
    reason: [
      'At risk on emissions reduction targets',
      'Energy sector overweight',
      'Limited transition plan credibility',
    ],
    expected_market_price_pct: 98.0,
    portfolio_impact: {
      exposure_reduction: 85000000,
      esg_score_improvement: 1.8,
      concentration_improvement: 3.2,
    },
    priority: 'medium',
  },
];

export const mockMarketBenchmarks: MarketBenchmark[] = [
  {
    metric_name: 'Portfolio ESG Score',
    metric_category: 'esg_performance',
    portfolio_value: 72,
    market_average: 68,
    top_quartile: 78,
    bottom_quartile: 58,
    percentile_rank: 72,
    unit: 'score',
    trend: 'improving',
  },
  {
    metric_name: 'Green Loan Allocation',
    metric_category: 'portfolio_composition',
    portfolio_value: 20.6,
    market_average: 25.3,
    top_quartile: 32,
    bottom_quartile: 15,
    percentile_rank: 42,
    unit: '%',
    trend: 'stable',
  },
  {
    metric_name: 'Weighted Avg Margin',
    metric_category: 'yield',
    portfolio_value: 195,
    market_average: 185,
    top_quartile: 210,
    bottom_quartile: 165,
    percentile_rank: 65,
    unit: 'bps',
    trend: 'stable',
  },
  {
    metric_name: 'Concentration Risk Score',
    metric_category: 'risk',
    portfolio_value: 68,
    market_average: 55,
    top_quartile: 45,
    bottom_quartile: 72,
    percentile_rank: 35,
    unit: 'score',
    trend: 'declining',
  },
  {
    metric_name: 'Carbon Intensity',
    metric_category: 'esg_performance',
    portfolio_value: 125,
    market_average: 142,
    top_quartile: 95,
    bottom_quartile: 185,
    percentile_rank: 68,
    unit: 'tCO2e/$M',
    trend: 'improving',
  },
  {
    metric_name: 'Target Achievement Rate',
    metric_category: 'esg_performance',
    portfolio_value: 71,
    market_average: 64,
    top_quartile: 82,
    bottom_quartile: 52,
    percentile_rank: 75,
    unit: '%',
    trend: 'improving',
  },
];

export const mockInstitutionalTargets: InstitutionalESGTarget[] = [
  {
    id: 'target-1',
    name: 'Net Zero Portfolio',
    description: 'Reduce portfolio carbon intensity by 50% by 2030',
    category: 'emissions',
    target_value: 75,
    current_value: 125,
    target_date: '2030-12-31',
    unit: 'tCO2e/$M',
    progress_percentage: 40,
    status: 'on_track',
    contributing_facilities: ['1', '2', '3'],
    gap_analysis: 'On track with current trajectory. Continue renewable energy focus.',
  },
  {
    id: 'target-2',
    name: 'Green Loan Minimum',
    description: 'Maintain minimum 30% green loan allocation',
    category: 'allocation',
    target_value: 30,
    current_value: 20.6,
    target_date: '2025-12-31',
    unit: '%',
    progress_percentage: 68.7,
    status: 'at_risk',
    contributing_facilities: ['2'],
    gap_analysis: 'Need to increase green loan participation by ~$80M to meet target.',
  },
  {
    id: 'target-3',
    name: 'Social Impact Minimum',
    description: 'Social loan allocation of at least 15%',
    category: 'allocation',
    target_value: 15,
    current_value: 11.8,
    target_date: '2025-12-31',
    unit: '%',
    progress_percentage: 78.7,
    status: 'at_risk',
    contributing_facilities: ['3'],
    gap_analysis: 'Gap of ~$27M in social loan exposure. Consider HealthTech syndication.',
  },
  {
    id: 'target-4',
    name: 'Portfolio ESG Rating',
    description: 'Achieve minimum A rating across portfolio',
    category: 'rating',
    target_value: 75,
    current_value: 72,
    target_date: '2025-06-30',
    unit: 'score',
    progress_percentage: 96,
    status: 'on_track',
    contributing_facilities: ['1', '2', '3', '5'],
    gap_analysis: 'Close to target. Divesting low performers would accelerate achievement.',
  },
];

export const mockDiversificationOpportunities: DiversificationOpportunity[] = [
  {
    id: 'div-1',
    title: 'Healthcare Sector Expansion',
    description: 'Healthcare sector significantly underweight vs target allocation. High ESG performers available.',
    category: 'sector',
    current_exposure_pct: 5.3,
    target_exposure_pct: 15,
    gap_amount: 82500000,
    potential_facilities: [mockSyndicationOpportunities[1]],
    expected_portfolio_impact: {
      esg_score_improvement: 2.1,
      risk_reduction_pct: 5.2,
      yield_impact_bps: -8,
    },
    priority: 'high',
  },
  {
    id: 'div-2',
    title: 'Green Loan Rebalancing',
    description: 'Green loan allocation below target and market average. Quality opportunities available.',
    category: 'loan_type',
    current_exposure_pct: 20.6,
    target_exposure_pct: 25,
    gap_amount: 37400000,
    potential_facilities: [mockSyndicationOpportunities[0], mockSyndicationOpportunities[3]],
    expected_portfolio_impact: {
      esg_score_improvement: 1.5,
      risk_reduction_pct: 3.8,
      yield_impact_bps: -5,
    },
    priority: 'high',
  },
  {
    id: 'div-3',
    title: 'Technology Sector Growth',
    description: 'Technology sector offers strong ESG performance with attractive yields.',
    category: 'sector',
    current_exposure_pct: 11.8,
    target_exposure_pct: 15,
    gap_amount: 27200000,
    potential_facilities: [mockSyndicationOpportunities[2]],
    expected_portfolio_impact: {
      esg_score_improvement: 0.8,
      risk_reduction_pct: 2.1,
      yield_impact_bps: -3,
    },
    priority: 'medium',
  },
];

export const mockOptimizationScenarios: PortfolioOptimizationScenario[] = [
  {
    id: 'scenario-opt-1',
    name: 'ESG Excellence',
    description: 'Maximize ESG score while maintaining yield. Focus on green and social loans.',
    type: 'aggressive_esg',
    target_allocations: {
      loan_type: {
        sustainability_linked: 35,
        green_loan: 30,
        social_loan: 20,
        transition_loan: 10,
        esg_linked_hybrid: 5,
      },
      sector: {
        energy: 20,
        real_estate: 20,
        manufacturing: 15,
        technology: 18,
        healthcare: 15,
        financial_services: 5,
        consumer_goods: 3,
        utilities: 2,
        transportation: 1,
        construction: 1,
      },
    },
    expected_outcomes: {
      portfolio_esg_score: 82,
      weighted_avg_yield_bps: 178,
      concentration_risk_score: 42,
      carbon_intensity_reduction_pct: 35,
    },
    required_actions: {
      participate: [mockSyndicationOpportunities[0], mockSyndicationOpportunities[1]],
      divest: [mockDivestmentCandidates[0]],
      estimated_execution_period: '6-9 months',
    },
    feasibility_score: 78,
  },
  {
    id: 'scenario-opt-2',
    name: 'Balanced Optimization',
    description: 'Balance ESG improvement with yield preservation and risk reduction.',
    type: 'balanced',
    target_allocations: {
      loan_type: {
        sustainability_linked: 40,
        green_loan: 25,
        social_loan: 15,
        transition_loan: 15,
        esg_linked_hybrid: 5,
      },
      sector: {
        energy: 22,
        real_estate: 20,
        manufacturing: 15,
        technology: 15,
        healthcare: 12,
        financial_services: 6,
        consumer_goods: 4,
        utilities: 3,
        transportation: 2,
        construction: 1,
      },
    },
    expected_outcomes: {
      portfolio_esg_score: 76,
      weighted_avg_yield_bps: 188,
      concentration_risk_score: 48,
      carbon_intensity_reduction_pct: 22,
    },
    required_actions: {
      participate: [mockSyndicationOpportunities[2]],
      divest: [mockDivestmentCandidates[1]],
      estimated_execution_period: '3-6 months',
    },
    feasibility_score: 85,
  },
  {
    id: 'scenario-opt-3',
    name: 'Risk Minimization',
    description: 'Reduce concentration risk and improve portfolio diversification.',
    type: 'risk_minimization',
    target_allocations: {
      loan_type: {
        sustainability_linked: 38,
        green_loan: 27,
        social_loan: 18,
        transition_loan: 12,
        esg_linked_hybrid: 5,
      },
      sector: {
        energy: 18,
        real_estate: 18,
        manufacturing: 14,
        technology: 16,
        healthcare: 14,
        financial_services: 8,
        consumer_goods: 5,
        utilities: 4,
        transportation: 2,
        construction: 1,
      },
    },
    expected_outcomes: {
      portfolio_esg_score: 74,
      weighted_avg_yield_bps: 182,
      concentration_risk_score: 38,
      carbon_intensity_reduction_pct: 18,
    },
    required_actions: {
      participate: [mockSyndicationOpportunities[1], mockSyndicationOpportunities[3]],
      divest: [mockDivestmentCandidates[0], mockDivestmentCandidates[1]],
      estimated_execution_period: '6-12 months',
    },
    feasibility_score: 72,
  },
];

export const mockOptimizationActions: OptimizationAction[] = [
  {
    id: 'action-opt-1',
    title: 'Reduce Energy Sector Concentration',
    description: 'Energy sector at 32.9% exceeds 25% limit. Divest Delta Transition Finance to bring within limits.',
    action_type: 'divest',
    priority: 'critical',
    expected_impact: 'Reduce energy concentration from 32.9% to 21.3%',
    target_metric: 'Sector Concentration',
    estimated_value: 180000000,
    deadline: '2025-03-31',
    related_facilities: ['4'],
  },
  {
    id: 'action-opt-2',
    title: 'Participate in Nordic Wind Green Loan',
    description: 'High-quality green loan opportunity. Would improve green allocation and portfolio ESG score.',
    action_type: 'participate',
    priority: 'high',
    expected_impact: 'Increase green loan allocation from 20.6% to 23.8%',
    target_metric: 'Green Loan Allocation',
    estimated_value: 50000000,
    deadline: '2025-01-31',
    related_facilities: ['synd-1'],
  },
  {
    id: 'action-opt-3',
    title: 'Healthcare Sector Entry',
    description: 'Healthcare underweight at 5.3% vs 15% target. HealthTech syndication provides entry point.',
    action_type: 'participate',
    priority: 'high',
    expected_impact: 'Increase healthcare allocation from 5.3% to 8.2%',
    target_metric: 'Sector Diversification',
    estimated_value: 35000000,
    deadline: '2025-02-15',
    related_facilities: ['synd-2'],
  },
  {
    id: 'action-opt-4',
    title: 'Monitor Legacy Mining Performance',
    description: 'At risk on KPIs. Set threshold for divestment if Q1 targets missed.',
    action_type: 'monitor',
    priority: 'medium',
    expected_impact: 'Proactive risk management',
    target_metric: 'ESG Performance',
    estimated_value: 85000000,
    deadline: '2025-03-31',
    related_facilities: ['7'],
  },
];

export const mockPortfolioOptimization: PortfolioOptimizationSummary = {
  generated_at: new Date().toISOString(),
  total_portfolio_value: 850000000,
  total_facilities: 12,
  portfolio_esg_score: mockPortfolioESGScore,
  concentration_analysis: mockConcentrationAnalysis,
  sector_allocation: mockSectorAllocation,
  loan_type_allocation: mockLoanTypeAllocation,
  diversification_opportunities: mockDiversificationOpportunities,
  syndication_opportunities: mockSyndicationOpportunities,
  divestment_candidates: mockDivestmentCandidates,
  market_benchmarks: mockMarketBenchmarks,
  institutional_targets: mockInstitutionalTargets,
  optimization_scenarios: mockOptimizationScenarios,
  recommended_actions: mockOptimizationActions,
};
