import type { ESGFacility, ESGFacilityDetail } from './types';

export const mockFacilities: ESGFacility[] = [
  {
    id: '1',
    facility_name: 'ABC Corp Sustainability-Linked Loan',
    borrower_name: 'ABC Corporation',
    borrower_industry: 'Manufacturing',
    esg_loan_type: 'sustainability_linked',
    commitment_amount: 150000000,
    outstanding_amount: 120000000,
    status: 'active',
    effective_date: '2024-01-15',
    maturity_date: '2029-01-15',
    framework_reference: 'LMA SLL Principles 2023',
    base_margin_bps: 200,
    current_margin_bps: 190,
    max_margin_adjustment_bps: 25,
    sustainability_coordinator: 'BNP Paribas',
    external_verifier: 'EY Assurance',
    kpi_count: 4,
    targets_achieved: 3,
    targets_total: 8,
    overall_performance_status: 'on_track',
    next_reporting_date: '2024-12-31',
    margin_adjustment_bps: -10,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    facility_name: 'XYZ Holdings Green Loan',
    borrower_name: 'XYZ Holdings Ltd',
    borrower_industry: 'Real Estate',
    esg_loan_type: 'green_loan',
    commitment_amount: 75000000,
    outstanding_amount: 75000000,
    status: 'active',
    effective_date: '2024-03-01',
    maturity_date: '2029-03-01',
    framework_reference: 'LMA Green Loan Principles 2023',
    base_margin_bps: 175,
    current_margin_bps: 175,
    max_margin_adjustment_bps: 0,
    sustainability_coordinator: 'HSBC',
    external_verifier: 'Sustainalytics',
    kpi_count: 2,
    targets_achieved: 1,
    targets_total: 4,
    overall_performance_status: 'at_risk',
    next_reporting_date: '2025-01-15',
    margin_adjustment_bps: 0,
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: '3',
    facility_name: 'Neptune Social Bond',
    borrower_name: 'Neptune Industries',
    borrower_industry: 'Construction',
    esg_loan_type: 'social_loan',
    commitment_amount: 100000000,
    outstanding_amount: 85000000,
    status: 'active',
    effective_date: '2024-02-20',
    maturity_date: '2028-02-20',
    framework_reference: 'LMA Social Loan Principles 2023',
    base_margin_bps: 185,
    current_margin_bps: 180,
    max_margin_adjustment_bps: 15,
    sustainability_coordinator: 'Deutsche Bank',
    external_verifier: 'DNV',
    kpi_count: 3,
    targets_achieved: 2,
    targets_total: 6,
    overall_performance_status: 'on_track',
    next_reporting_date: '2025-02-01',
    margin_adjustment_bps: -5,
    created_at: '2024-02-20T00:00:00Z',
  },
  {
    id: '4',
    facility_name: 'Delta Transition Finance',
    borrower_name: 'Delta Energy Corp',
    borrower_industry: 'Energy',
    esg_loan_type: 'transition_loan',
    commitment_amount: 200000000,
    outstanding_amount: 180000000,
    status: 'active',
    effective_date: '2024-04-10',
    maturity_date: '2030-04-10',
    framework_reference: 'Climate Transition Finance Handbook',
    base_margin_bps: 225,
    current_margin_bps: 240,
    max_margin_adjustment_bps: 30,
    sustainability_coordinator: 'Barclays',
    external_verifier: 'KPMG',
    kpi_count: 5,
    targets_achieved: 1,
    targets_total: 10,
    overall_performance_status: 'off_track',
    next_reporting_date: '2024-12-15',
    margin_adjustment_bps: 15,
    created_at: '2024-04-10T00:00:00Z',
  },
  {
    id: '5',
    facility_name: 'Omega ESG Hybrid',
    borrower_name: 'Omega Tech Inc',
    borrower_industry: 'Technology',
    esg_loan_type: 'esg_linked_hybrid',
    commitment_amount: 50000000,
    outstanding_amount: 0,
    status: 'pending',
    effective_date: '2024-11-01',
    maturity_date: '2029-11-01',
    framework_reference: 'LMA ESG Principles 2023',
    base_margin_bps: 195,
    current_margin_bps: 195,
    max_margin_adjustment_bps: 20,
    kpi_count: 0,
    targets_achieved: 0,
    targets_total: 0,
    overall_performance_status: 'pending',
    next_reporting_date: null,
    margin_adjustment_bps: 0,
    created_at: '2024-11-01T00:00:00Z',
  },
];

export const mockFacilityDetail: ESGFacilityDetail = {
  ...mockFacilities[0],
  kpis: [
    {
      id: '1',
      kpi_name: 'Scope 1 & 2 GHG Emissions',
      kpi_category: 'environmental_emissions',
      unit: 'tCO2e',
      baseline_value: 50000,
      baseline_year: 2023,
      current_value: 42000,
      weight: 35,
      is_active: true,
      targets: [
        { target_year: 2024, target_value: 45000, target_status: 'achieved', actual_value: 42000 },
        { target_year: 2025, target_value: 40000, target_status: 'on_track' },
        { target_year: 2026, target_value: 35000, target_status: 'pending' },
      ],
    },
    {
      id: '2',
      kpi_name: 'Renewable Energy Share',
      kpi_category: 'environmental_energy',
      unit: '%',
      baseline_value: 25,
      baseline_year: 2023,
      current_value: 42,
      weight: 25,
      is_active: true,
      targets: [
        { target_year: 2024, target_value: 35, target_status: 'achieved', actual_value: 42 },
        { target_year: 2025, target_value: 50, target_status: 'at_risk' },
        { target_year: 2026, target_value: 65, target_status: 'pending' },
      ],
    },
    {
      id: '3',
      kpi_name: 'Women in Leadership',
      kpi_category: 'social_workforce',
      unit: '%',
      baseline_value: 22,
      baseline_year: 2023,
      current_value: 28,
      weight: 20,
      is_active: true,
      targets: [
        { target_year: 2024, target_value: 25, target_status: 'achieved', actual_value: 28 },
        { target_year: 2025, target_value: 30, target_status: 'on_track' },
        { target_year: 2026, target_value: 35, target_status: 'pending' },
      ],
    },
    {
      id: '4',
      kpi_name: 'Lost Time Injury Rate',
      kpi_category: 'social_health_safety',
      unit: 'per 1M hours',
      baseline_value: 2.5,
      baseline_year: 2023,
      current_value: 1.8,
      weight: 20,
      is_active: true,
      targets: [
        { target_year: 2024, target_value: 2.0, target_status: 'achieved', actual_value: 1.8 },
        { target_year: 2025, target_value: 1.5, target_status: 'on_track' },
        { target_year: 2026, target_value: 1.0, target_status: 'pending' },
      ],
    },
  ],
  ratings: [
    { provider: 'msci', rating: 'AA', rating_date: '2024-06-15', outlook: 'stable' },
    { provider: 'sustainalytics', rating: '18.5 (Low Risk)', rating_date: '2024-07-01' },
    { provider: 'cdp', rating: 'A-', rating_date: '2024-09-01' },
  ],
  reports: [
    { id: '1', report_type: 'annual', status: 'submitted', period_end: '2023-12-31', submitted_at: '2024-02-28' },
    { id: '2', report_type: 'quarterly', status: 'submitted', period_end: '2024-03-31', submitted_at: '2024-04-15' },
    { id: '3', report_type: 'quarterly', status: 'submitted', period_end: '2024-06-30', submitted_at: '2024-07-20' },
    { id: '4', report_type: 'quarterly', status: 'draft', period_end: '2024-09-30' },
  ],
  margin_history: [
    { period: 'Q1 2024', adjustment_bps: -5, cumulative_bps: -5 },
    { period: 'Q2 2024', adjustment_bps: -5, cumulative_bps: -10 },
    { period: 'Q3 2024', adjustment_bps: 0, cumulative_bps: -10 },
  ],
};
