/**
 * Autonomous Document Evolution Engine Types
 *
 * Types for monitoring market conditions, regulatory changes, and portfolio performance
 * to proactively suggest document amendments before problems occur.
 */

// =============================================================================
// Market Condition Types
// =============================================================================

/**
 * Interest rate data from market sources
 */
export interface InterestRateData {
  /** Rate identifier (e.g., SOFR, Prime, LIBOR) */
  rateType: string;
  /** Current rate value */
  currentRate: number;
  /** Previous rate value */
  previousRate: number;
  /** Rate change in basis points */
  changeBps: number;
  /** Direction of movement */
  direction: 'up' | 'down' | 'unchanged';
  /** As-of date */
  asOfDate: string;
  /** 30-day moving average */
  movingAverage30d?: number;
  /** 90-day moving average */
  movingAverage90d?: number;
  /** Historical data points */
  history?: Array<{ date: string; rate: number }>;
}

/**
 * Credit spread data for market monitoring
 */
export interface CreditSpreadData {
  /** Spread identifier */
  spreadType: string;
  /** Credit rating category */
  rating: 'AAA' | 'AA' | 'A' | 'BBB' | 'BB' | 'B' | 'CCC' | 'unrated';
  /** Sector/industry */
  sector?: string;
  /** Current spread in basis points */
  currentSpread: number;
  /** Previous spread */
  previousSpread: number;
  /** Change in basis points */
  changeBps: number;
  /** Spread direction */
  direction: 'widening' | 'tightening' | 'unchanged';
  /** As-of date */
  asOfDate: string;
  /** Percentile vs historical range */
  historicalPercentile?: number;
}

/**
 * Regulatory announcement from monitoring
 */
export interface RegulatoryAnnouncement {
  /** Unique identifier */
  id: string;
  /** Regulatory body */
  regulator: string;
  /** Announcement title */
  title: string;
  /** Summary of announcement */
  summary: string;
  /** Categories affected */
  categories: string[];
  /** Publication date */
  publishedDate: string;
  /** Effective date (if applicable) */
  effectiveDate?: string;
  /** Impact assessment */
  impactLevel: 'info' | 'low' | 'medium' | 'high' | 'critical';
  /** Link to source */
  sourceUrl?: string;
  /** Affected document types */
  affectedDocumentTypes?: string[];
  /** Key requirements */
  keyRequirements?: string[];
}

/**
 * Covenant headroom analysis for a facility
 */
export interface CovenantHeadroomAnalysis {
  /** Covenant identifier */
  covenantId: string;
  /** Covenant name */
  covenantName: string;
  /** Covenant type */
  covenantType: string;
  /** Facility identifier */
  facilityId: string;
  /** Current headroom percentage */
  currentHeadroom: number;
  /** Threshold value */
  thresholdValue: number;
  /** Current value */
  currentValue: number;
  /** Threshold type */
  thresholdType: 'maximum' | 'minimum';
  /** Risk level based on headroom */
  riskLevel: 'safe' | 'comfortable' | 'tight' | 'at_risk' | 'breached';
  /** Trend direction */
  trend: 'improving' | 'stable' | 'deteriorating';
  /** Months until projected breach (null if not projected) */
  monthsToProjectedBreach?: number | null;
  /** Test history */
  testHistory: Array<{
    date: string;
    value: number;
    headroom: number;
    result: 'pass' | 'fail' | 'waived';
  }>;
}

/**
 * Aggregated market conditions snapshot
 */
export interface MarketConditionsSnapshot {
  /** Snapshot timestamp */
  timestamp: string;
  /** Interest rate data */
  interestRates: InterestRateData[];
  /** Credit spread data */
  creditSpreads: CreditSpreadData[];
  /** Recent regulatory announcements */
  regulatoryAnnouncements: RegulatoryAnnouncement[];
  /** Market sentiment indicators */
  marketSentiment: {
    overall: 'bullish' | 'neutral' | 'bearish';
    volatilityIndex?: number;
    economicOutlook?: 'expansion' | 'stable' | 'contraction';
  };
  /** Data quality indicators */
  dataQuality: {
    completeness: number;
    freshness: number;
    sources: string[];
  };
}

// =============================================================================
// Amendment Suggestion Types
// =============================================================================

/**
 * Proactive amendment suggestion generated by the evolution engine
 */
export interface AmendmentSuggestion {
  /** Unique identifier */
  id: string;
  /** Facility identifier */
  facilityId: string;
  /** Document identifier */
  documentId: string;
  /** Suggestion type */
  type: AmendmentSuggestionType;
  /** Priority level */
  priority: 'low' | 'medium' | 'high' | 'urgent';
  /** Suggestion title */
  title: string;
  /** Detailed description */
  description: string;
  /** Business rationale */
  rationale: string;
  /** Triggering conditions */
  triggerConditions: AmendmentTrigger[];
  /** Suggested changes */
  suggestedChanges: SuggestedChange[];
  /** Negotiation points to consider */
  negotiationPoints: NegotiationPoint[];
  /** Risk assessment if not acted upon */
  riskIfIgnored: {
    likelihood: 'low' | 'medium' | 'high';
    impact: 'minimal' | 'moderate' | 'significant' | 'severe';
    description: string;
  };
  /** Estimated timeline to address */
  estimatedTimeline: string;
  /** Confidence score */
  confidence: number;
  /** Status of suggestion */
  status: 'new' | 'under_review' | 'approved' | 'in_progress' | 'completed' | 'dismissed';
  /** Created timestamp */
  createdAt: string;
  /** Last updated timestamp */
  updatedAt: string;
  /** Related suggestions */
  relatedSuggestionIds?: string[];
}

/**
 * Types of amendment suggestions
 */
export type AmendmentSuggestionType =
  | 'covenant_reset'           // Reset covenant levels due to market changes
  | 'margin_adjustment'        // Adjust margin based on market rates
  | 'maturity_extension'       // Extend maturity based on conditions
  | 'commitment_change'        // Increase/decrease facility size
  | 'regulatory_compliance'    // Address regulatory requirements
  | 'definition_update'        // Update definitions (e.g., LIBOR to SOFR)
  | 'waiver_preemptive'        // Preemptive waiver request
  | 'structural_change'        // Change facility structure
  | 'collateral_adjustment'    // Adjust collateral requirements
  | 'reporting_frequency'      // Change reporting requirements
  | 'cure_rights_enhancement'  // Enhance cure rights provisions
  | 'basket_adjustment';       // Adjust permitted baskets

/**
 * Trigger that prompted an amendment suggestion
 */
export interface AmendmentTrigger {
  /** Trigger type */
  type: 'market_condition' | 'covenant_headroom' | 'regulatory' | 'portfolio_performance' | 'time_based';
  /** Trigger description */
  description: string;
  /** Metric or indicator name */
  indicator?: string;
  /** Current value */
  currentValue?: number | string;
  /** Threshold that triggered */
  threshold?: number | string;
  /** Data source */
  source: string;
  /** Timestamp of trigger */
  triggeredAt: string;
}

/**
 * Suggested change to document terms
 */
export interface SuggestedChange {
  /** Field or clause being changed */
  field: string;
  /** Category of change */
  category: string;
  /** Current value */
  currentValue: string | number | null;
  /** Suggested new value */
  suggestedValue: string | number;
  /** Change rationale */
  rationale: string;
  /** Impact assessment */
  impact: {
    financial?: string;
    operational?: string;
    legal?: string;
  };
  /** Draft clause language */
  draftLanguage?: string;
  /** Clause reference in original document */
  clauseReference?: string;
}

/**
 * Pre-populated negotiation point
 */
export interface NegotiationPoint {
  /** Point title */
  title: string;
  /** Our position (lender/agent perspective) */
  ourPosition: string;
  /** Anticipated counterparty position */
  anticipatedCounterposition: string;
  /** Fallback position */
  fallbackPosition?: string;
  /** Priority in negotiation */
  priority: 'must_have' | 'important' | 'nice_to_have';
  /** Supporting arguments */
  supportingArguments: string[];
  /** Market precedent */
  marketPrecedent?: string;
}

// =============================================================================
// Evolution Engine State & Configuration
// =============================================================================

/**
 * Configuration for the evolution engine monitoring
 */
export interface EvolutionEngineConfig {
  /** Monitoring interval in hours */
  monitoringIntervalHours: number;
  /** Interest rate change threshold (bps) for alerts */
  interestRateAlertThresholdBps: number;
  /** Credit spread change threshold (bps) for alerts */
  creditSpreadAlertThresholdBps: number;
  /** Covenant headroom threshold (%) for alerts */
  covenantHeadroomAlertThreshold: number;
  /** Days before maturity to alert */
  maturityAlertDays: number;
  /** Auto-generate amendment suggestions */
  autoGenerateSuggestions: boolean;
  /** Enabled trigger types */
  enabledTriggerTypes: AmendmentTrigger['type'][];
  /** Facilities to monitor (empty = all) */
  monitoredFacilityIds: string[];
  /** Notification settings */
  notifications: {
    email: boolean;
    inApp: boolean;
    webhook?: string;
  };
}

/**
 * Evolution engine monitoring status
 */
export interface EvolutionEngineStatus {
  /** Whether engine is running */
  isRunning: boolean;
  /** Last monitoring run timestamp */
  lastRunAt: string | null;
  /** Next scheduled run */
  nextRunAt: string | null;
  /** Number of facilities being monitored */
  facilitiesMonitored: number;
  /** Active suggestion count */
  activeSuggestions: number;
  /** Recent alerts */
  recentAlerts: EvolutionAlert[];
  /** Engine health */
  health: {
    status: 'healthy' | 'degraded' | 'error';
    message?: string;
    lastError?: string;
  };
}

/**
 * Alert from the evolution engine
 */
export interface EvolutionAlert {
  /** Alert identifier */
  id: string;
  /** Alert type */
  type: 'market_movement' | 'covenant_risk' | 'regulatory_change' | 'suggestion_generated' | 'action_required';
  /** Severity */
  severity: 'info' | 'warning' | 'critical';
  /** Alert title */
  title: string;
  /** Alert message */
  message: string;
  /** Related entity */
  relatedEntity?: {
    type: 'facility' | 'document' | 'suggestion' | 'covenant';
    id: string;
    name: string;
  };
  /** Created timestamp */
  createdAt: string;
  /** Read status */
  isRead: boolean;
  /** Dismissed status */
  isDismissed: boolean;
}

// =============================================================================
// Dashboard & Analytics Types
// =============================================================================

/**
 * Evolution dashboard summary statistics
 */
export interface EvolutionDashboardStats {
  /** Total facilities monitored */
  totalFacilitiesMonitored: number;
  /** Facilities with active suggestions */
  facilitiesWithSuggestions: number;
  /** Total active amendment suggestions */
  activeSuggestions: number;
  /** Suggestions by priority */
  suggestionsByPriority: {
    urgent: number;
    high: number;
    medium: number;
    low: number;
  };
  /** Suggestions by type */
  suggestionsByType: Record<AmendmentSuggestionType, number>;
  /** Covenants at risk */
  covenantsAtRisk: number;
  /** Average covenant headroom */
  averageCovenantHeadroom: number;
  /** Market conditions summary */
  marketConditionsSummary: {
    interestRateTrend: 'rising' | 'falling' | 'stable';
    creditSpreadTrend: 'widening' | 'tightening' | 'stable';
    recentRegulatoryChanges: number;
  };
  /** Engine status */
  engineStatus: EvolutionEngineStatus;
  /** Recent activity */
  recentActivity: Array<{
    type: string;
    description: string;
    timestamp: string;
    entityId?: string;
    entityName?: string;
  }>;
}

/**
 * Facility evolution status
 */
export interface FacilityEvolutionStatus {
  /** Facility identifier */
  facilityId: string;
  /** Facility name */
  facilityName: string;
  /** Borrower name */
  borrowerName: string;
  /** Overall health score (0-100) */
  healthScore: number;
  /** Health trend */
  healthTrend: 'improving' | 'stable' | 'deteriorating';
  /** Active suggestions for this facility */
  activeSuggestions: AmendmentSuggestion[];
  /** Covenant headroom analysis */
  covenantAnalysis: CovenantHeadroomAnalysis[];
  /** Market exposure assessment */
  marketExposure: {
    interestRateSensitivity: 'low' | 'medium' | 'high';
    creditSpreadExposure: 'minimal' | 'moderate' | 'significant';
    regulatoryRisk: 'low' | 'medium' | 'high';
  };
  /** Recent changes */
  recentChanges: Array<{
    type: string;
    description: string;
    date: string;
    impact: 'positive' | 'neutral' | 'negative';
  }>;
  /** Maturity information */
  maturity: {
    date: string;
    daysUntil: number;
    actionRequired: boolean;
  };
  /** Last analyzed timestamp */
  lastAnalyzedAt: string;
}

// =============================================================================
// API Request/Response Types
// =============================================================================

/**
 * Request to analyze facility for evolution suggestions
 */
export interface AnalyzeFacilityRequest {
  facilityId: string;
  includeMarketAnalysis?: boolean;
  includeCovenantAnalysis?: boolean;
  includeRegulatoryAnalysis?: boolean;
  forceRefresh?: boolean;
}

/**
 * Response from facility analysis
 */
export interface AnalyzeFacilityResponse {
  facilityId: string;
  status: FacilityEvolutionStatus;
  suggestions: AmendmentSuggestion[];
  marketConditions: MarketConditionsSnapshot;
  analyzedAt: string;
}

/**
 * Request to generate amendment suggestion
 */
export interface GenerateSuggestionRequest {
  facilityId: string;
  documentId: string;
  suggestionType: AmendmentSuggestionType;
  triggerDescription?: string;
  customContext?: Record<string, unknown>;
}

/**
 * Request to initiate counterparty communication
 */
export interface InitiateCommunicationRequest {
  suggestionId: string;
  communicationType: 'informal_discussion' | 'formal_proposal' | 'amendment_request';
  recipients: Array<{
    name: string;
    email: string;
    role: string;
  }>;
  customMessage?: string;
  attachDraftAmendment?: boolean;
}

/**
 * Response from initiating communication
 */
export interface InitiateCommunicationResponse {
  success: boolean;
  communicationId: string;
  status: 'scheduled' | 'sent' | 'failed';
  sentAt?: string;
  error?: string;
}
