export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          type: 'bank' | 'borrower' | 'law_firm' | 'agent' | 'other';
          settings: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: 'bank' | 'borrower' | 'law_firm' | 'agent' | 'other';
          settings?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: 'bank' | 'borrower' | 'law_firm' | 'agent' | 'other';
          settings?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          organization_id: string;
          email: string;
          full_name: string;
          role: 'admin' | 'manager' | 'user' | 'viewer';
          preferences: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          organization_id: string;
          email: string;
          full_name: string;
          role?: 'admin' | 'manager' | 'user' | 'viewer';
          preferences?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          email?: string;
          full_name?: string;
          role?: 'admin' | 'manager' | 'user' | 'viewer';
          preferences?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      loan_documents: {
        Row: {
          id: string;
          organization_id: string;
          uploaded_by: string;
          uploaded_at: string;
          original_filename: string;
          storage_path: string;
          document_type: 'facility_agreement' | 'amendment' | 'consent' | 'assignment' | 'other';
          processing_status: 'pending' | 'processing' | 'completed' | 'failed' | 'review_required';
          extraction_version: number;
          raw_text: string | null;
          page_count: number | null;
          file_size: number | null;
          error_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          uploaded_by: string;
          uploaded_at?: string;
          original_filename: string;
          storage_path: string;
          document_type?: 'facility_agreement' | 'amendment' | 'consent' | 'assignment' | 'other';
          processing_status?: 'pending' | 'processing' | 'completed' | 'failed' | 'review_required';
          extraction_version?: number;
          raw_text?: string | null;
          page_count?: number | null;
          file_size?: number | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          uploaded_by?: string;
          uploaded_at?: string;
          original_filename?: string;
          storage_path?: string;
          document_type?: 'facility_agreement' | 'amendment' | 'consent' | 'assignment' | 'other';
          processing_status?: 'pending' | 'processing' | 'completed' | 'failed' | 'review_required';
          extraction_version?: number;
          raw_text?: string | null;
          page_count?: number | null;
          file_size?: number | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      loan_facilities: {
        Row: {
          id: string;
          organization_id: string;
          source_document_id: string;
          facility_name: string;
          facility_reference: string | null;
          execution_date: string | null;
          effective_date: string | null;
          maturity_date: string | null;
          borrowers: Json | null;
          guarantors: Json | null;
          lenders: Json | null;
          agents: Json | null;
          facility_type: 'term' | 'revolving' | 'delayed_draw' | 'swingline' | 'other';
          currency: string;
          total_commitments: number | null;
          interest_rate_type: 'floating' | 'fixed' | 'hybrid' | null;
          base_rate: string | null;
          margin_initial: number | null;
          margin_grid: Json | null;
          commitment_fee: number | null;
          utilization_fee: Json | null;
          arrangement_fee: number | null;
          governing_law: string | null;
          jurisdiction: string | null;
          syndicated: boolean;
          extraction_confidence: number;
          status: 'active' | 'closed' | 'defaulted';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          source_document_id: string;
          facility_name: string;
          facility_reference?: string | null;
          execution_date?: string | null;
          effective_date?: string | null;
          maturity_date?: string | null;
          borrowers?: Json | null;
          guarantors?: Json | null;
          lenders?: Json | null;
          agents?: Json | null;
          facility_type?: 'term' | 'revolving' | 'delayed_draw' | 'swingline' | 'other';
          currency?: string;
          total_commitments?: number | null;
          interest_rate_type?: 'floating' | 'fixed' | 'hybrid' | null;
          base_rate?: string | null;
          margin_initial?: number | null;
          margin_grid?: Json | null;
          commitment_fee?: number | null;
          utilization_fee?: Json | null;
          arrangement_fee?: number | null;
          governing_law?: string | null;
          jurisdiction?: string | null;
          syndicated?: boolean;
          extraction_confidence?: number;
          status?: 'active' | 'closed' | 'defaulted';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          source_document_id?: string;
          facility_name?: string;
          facility_reference?: string | null;
          execution_date?: string | null;
          effective_date?: string | null;
          maturity_date?: string | null;
          borrowers?: Json | null;
          guarantors?: Json | null;
          lenders?: Json | null;
          agents?: Json | null;
          facility_type?: 'term' | 'revolving' | 'delayed_draw' | 'swingline' | 'other';
          currency?: string;
          total_commitments?: number | null;
          interest_rate_type?: 'floating' | 'fixed' | 'hybrid' | null;
          base_rate?: string | null;
          margin_initial?: number | null;
          margin_grid?: Json | null;
          commitment_fee?: number | null;
          utilization_fee?: Json | null;
          arrangement_fee?: number | null;
          governing_law?: string | null;
          jurisdiction?: string | null;
          syndicated?: boolean;
          extraction_confidence?: number;
          status?: 'active' | 'closed' | 'defaulted';
          created_at?: string;
          updated_at?: string;
        };
      };
      financial_covenants: {
        Row: {
          id: string;
          facility_id: string;
          source_document_id: string;
          covenant_type: 'leverage_ratio' | 'interest_coverage' | 'debt_service_coverage' | 'net_worth' | 'current_ratio' | 'capex_limit' | 'other';
          covenant_name: string;
          numerator_definition: string | null;
          denominator_definition: string | null;
          calculation_methodology: string | null;
          threshold_type: 'maximum' | 'minimum' | 'range';
          threshold_value: number | null;
          threshold_schedule: Json | null;
          testing_frequency: 'quarterly' | 'semi_annual' | 'annual';
          testing_dates: Json | null;
          cure_rights: string | null;
          clause_reference: string | null;
          page_number: number | null;
          raw_text: string | null;
          extraction_confidence: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          facility_id: string;
          source_document_id: string;
          covenant_type: 'leverage_ratio' | 'interest_coverage' | 'debt_service_coverage' | 'net_worth' | 'current_ratio' | 'capex_limit' | 'other';
          covenant_name: string;
          numerator_definition?: string | null;
          denominator_definition?: string | null;
          calculation_methodology?: string | null;
          threshold_type?: 'maximum' | 'minimum' | 'range';
          threshold_value?: number | null;
          threshold_schedule?: Json | null;
          testing_frequency?: 'quarterly' | 'semi_annual' | 'annual';
          testing_dates?: Json | null;
          cure_rights?: string | null;
          clause_reference?: string | null;
          page_number?: number | null;
          raw_text?: string | null;
          extraction_confidence?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          facility_id?: string;
          source_document_id?: string;
          covenant_type?: 'leverage_ratio' | 'interest_coverage' | 'debt_service_coverage' | 'net_worth' | 'current_ratio' | 'capex_limit' | 'other';
          covenant_name?: string;
          numerator_definition?: string | null;
          denominator_definition?: string | null;
          calculation_methodology?: string | null;
          threshold_type?: 'maximum' | 'minimum' | 'range';
          threshold_value?: number | null;
          threshold_schedule?: Json | null;
          testing_frequency?: 'quarterly' | 'semi_annual' | 'annual';
          testing_dates?: Json | null;
          cure_rights?: string | null;
          clause_reference?: string | null;
          page_number?: number | null;
          raw_text?: string | null;
          extraction_confidence?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      reporting_obligations: {
        Row: {
          id: string;
          facility_id: string;
          source_document_id: string;
          obligation_type: 'annual_financials' | 'quarterly_financials' | 'compliance_certificate' | 'budget' | 'audit_report' | 'event_notice' | 'other';
          description: string | null;
          frequency: 'annual' | 'quarterly' | 'monthly' | 'on_occurrence' | 'other';
          deadline_days: number | null;
          deadline_description: string | null;
          recipient_role: string | null;
          clause_reference: string | null;
          page_number: number | null;
          raw_text: string | null;
          extraction_confidence: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          facility_id: string;
          source_document_id: string;
          obligation_type: 'annual_financials' | 'quarterly_financials' | 'compliance_certificate' | 'budget' | 'audit_report' | 'event_notice' | 'other';
          description?: string | null;
          frequency?: 'annual' | 'quarterly' | 'monthly' | 'on_occurrence' | 'other';
          deadline_days?: number | null;
          deadline_description?: string | null;
          recipient_role?: string | null;
          clause_reference?: string | null;
          page_number?: number | null;
          raw_text?: string | null;
          extraction_confidence?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          facility_id?: string;
          source_document_id?: string;
          obligation_type?: 'annual_financials' | 'quarterly_financials' | 'compliance_certificate' | 'budget' | 'audit_report' | 'event_notice' | 'other';
          description?: string | null;
          frequency?: 'annual' | 'quarterly' | 'monthly' | 'on_occurrence' | 'other';
          deadline_days?: number | null;
          deadline_description?: string | null;
          recipient_role?: string | null;
          clause_reference?: string | null;
          page_number?: number | null;
          raw_text?: string | null;
          extraction_confidence?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      events_of_default: {
        Row: {
          id: string;
          facility_id: string;
          source_document_id: string;
          event_category: 'payment_default' | 'covenant_breach' | 'representation_breach' | 'cross_default' | 'insolvency' | 'material_adverse_change' | 'change_of_control' | 'other';
          description: string | null;
          grace_period_days: number | null;
          cure_rights: string | null;
          consequences: string | null;
          clause_reference: string | null;
          page_number: number | null;
          raw_text: string | null;
          extraction_confidence: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          facility_id: string;
          source_document_id: string;
          event_category: 'payment_default' | 'covenant_breach' | 'representation_breach' | 'cross_default' | 'insolvency' | 'material_adverse_change' | 'change_of_control' | 'other';
          description?: string | null;
          grace_period_days?: number | null;
          cure_rights?: string | null;
          consequences?: string | null;
          clause_reference?: string | null;
          page_number?: number | null;
          raw_text?: string | null;
          extraction_confidence?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          facility_id?: string;
          source_document_id?: string;
          event_category?: 'payment_default' | 'covenant_breach' | 'representation_breach' | 'cross_default' | 'insolvency' | 'material_adverse_change' | 'change_of_control' | 'other';
          description?: string | null;
          grace_period_days?: number | null;
          cure_rights?: string | null;
          consequences?: string | null;
          clause_reference?: string | null;
          page_number?: number | null;
          raw_text?: string | null;
          extraction_confidence?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      esg_provisions: {
        Row: {
          id: string;
          facility_id: string;
          source_document_id: string;
          provision_type: 'sustainability_linked_margin' | 'green_use_of_proceeds' | 'esg_reporting' | 'esg_covenant' | 'other';
          kpi_name: string | null;
          kpi_definition: string | null;
          kpi_baseline: number | null;
          kpi_targets: Json | null;
          verification_required: boolean;
          verifier_requirements: string | null;
          clause_reference: string | null;
          page_number: number | null;
          raw_text: string | null;
          extraction_confidence: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          facility_id: string;
          source_document_id: string;
          provision_type: 'sustainability_linked_margin' | 'green_use_of_proceeds' | 'esg_reporting' | 'esg_covenant' | 'other';
          kpi_name?: string | null;
          kpi_definition?: string | null;
          kpi_baseline?: number | null;
          kpi_targets?: Json | null;
          verification_required?: boolean;
          verifier_requirements?: string | null;
          clause_reference?: string | null;
          page_number?: number | null;
          raw_text?: string | null;
          extraction_confidence?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          facility_id?: string;
          source_document_id?: string;
          provision_type?: 'sustainability_linked_margin' | 'green_use_of_proceeds' | 'esg_reporting' | 'esg_covenant' | 'other';
          kpi_name?: string | null;
          kpi_definition?: string | null;
          kpi_baseline?: number | null;
          kpi_targets?: Json | null;
          verification_required?: boolean;
          verifier_requirements?: string | null;
          clause_reference?: string | null;
          page_number?: number | null;
          raw_text?: string | null;
          extraction_confidence?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      defined_terms: {
        Row: {
          id: string;
          facility_id: string;
          source_document_id: string;
          term: string;
          definition: string;
          clause_reference: string | null;
          page_number: number | null;
          references_terms: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          facility_id: string;
          source_document_id: string;
          term: string;
          definition: string;
          clause_reference?: string | null;
          page_number?: number | null;
          references_terms?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          facility_id?: string;
          source_document_id?: string;
          term?: string;
          definition?: string;
          clause_reference?: string | null;
          page_number?: number | null;
          references_terms?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          source_module: 'documents' | 'deals' | 'compliance' | 'trading' | 'esg';
          notification_type: string;
          title: string;
          message: string | null;
          related_entity_type: string | null;
          related_entity_id: string | null;
          action_url: string | null;
          is_read: boolean;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          source_module: 'documents' | 'deals' | 'compliance' | 'trading' | 'esg';
          notification_type: string;
          title: string;
          message?: string | null;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          action_url?: string | null;
          is_read?: boolean;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          user_id?: string;
          source_module?: 'documents' | 'deals' | 'compliance' | 'trading' | 'esg';
          notification_type?: string;
          title?: string;
          message?: string | null;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          action_url?: string | null;
          is_read?: boolean;
          read_at?: string | null;
          created_at?: string;
        };
      };
      activities: {
        Row: {
          id: string;
          organization_id: string;
          source_module: 'documents' | 'deals' | 'compliance' | 'trading' | 'esg';
          activity_type: string;
          actor_id: string;
          entity_type: string;
          entity_id: string;
          entity_name: string | null;
          description: string;
          details: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          source_module: 'documents' | 'deals' | 'compliance' | 'trading' | 'esg';
          activity_type: string;
          actor_id: string;
          entity_type: string;
          entity_id: string;
          entity_name?: string | null;
          description: string;
          details?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          source_module?: 'documents' | 'deals' | 'compliance' | 'trading' | 'esg';
          activity_type?: string;
          actor_id?: string;
          entity_type?: string;
          entity_id?: string;
          entity_name?: string | null;
          description?: string;
          details?: Json | null;
          created_at?: string;
        };
      };
      // Deal Room Module
      deals: {
        Row: {
          id: string;
          organization_id: string;
          deal_name: string;
          deal_reference: string | null;
          deal_type: 'new_facility' | 'amendment' | 'refinancing' | 'restructuring';
          base_facility_id: string | null;
          status: 'draft' | 'active' | 'paused' | 'agreed' | 'closed' | 'terminated';
          negotiation_mode: 'bilateral' | 'multilateral';
          require_unanimous_consent: boolean;
          auto_lock_agreed_terms: boolean;
          target_signing_date: string | null;
          target_closing_date: string | null;
          created_at: string;
          updated_at: string;
          created_by: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          deal_name: string;
          deal_reference?: string | null;
          deal_type: 'new_facility' | 'amendment' | 'refinancing' | 'restructuring';
          base_facility_id?: string | null;
          status?: 'draft' | 'active' | 'paused' | 'agreed' | 'closed' | 'terminated';
          negotiation_mode?: 'bilateral' | 'multilateral';
          require_unanimous_consent?: boolean;
          auto_lock_agreed_terms?: boolean;
          target_signing_date?: string | null;
          target_closing_date?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          deal_name?: string;
          deal_reference?: string | null;
          deal_type?: 'new_facility' | 'amendment' | 'refinancing' | 'restructuring';
          base_facility_id?: string | null;
          status?: 'draft' | 'active' | 'paused' | 'agreed' | 'closed' | 'terminated';
          negotiation_mode?: 'bilateral' | 'multilateral';
          require_unanimous_consent?: boolean;
          auto_lock_agreed_terms?: boolean;
          target_signing_date?: string | null;
          target_closing_date?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string;
        };
      };
      deal_participants: {
        Row: {
          id: string;
          deal_id: string;
          user_id: string;
          party_name: string;
          party_type: 'borrower_side' | 'lender_side' | 'third_party';
          party_role: string;
          deal_role: 'deal_lead' | 'negotiator' | 'reviewer' | 'observer';
          can_approve: boolean;
          invited_at: string;
          joined_at: string | null;
          status: 'pending' | 'active' | 'removed';
        };
        Insert: {
          id?: string;
          deal_id: string;
          user_id: string;
          party_name: string;
          party_type: 'borrower_side' | 'lender_side' | 'third_party';
          party_role: string;
          deal_role?: 'deal_lead' | 'negotiator' | 'reviewer' | 'observer';
          can_approve?: boolean;
          invited_at?: string;
          joined_at?: string | null;
          status?: 'pending' | 'active' | 'removed';
        };
        Update: {
          id?: string;
          deal_id?: string;
          user_id?: string;
          party_name?: string;
          party_type?: 'borrower_side' | 'lender_side' | 'third_party';
          party_role?: string;
          deal_role?: 'deal_lead' | 'negotiator' | 'reviewer' | 'observer';
          can_approve?: boolean;
          invited_at?: string;
          joined_at?: string | null;
          status?: 'pending' | 'active' | 'removed';
        };
      };
      term_categories: {
        Row: {
          id: string;
          deal_id: string;
          name: string;
          display_order: number;
          parent_category_id: string | null;
        };
        Insert: {
          id?: string;
          deal_id: string;
          name: string;
          display_order?: number;
          parent_category_id?: string | null;
        };
        Update: {
          id?: string;
          deal_id?: string;
          name?: string;
          display_order?: number;
          parent_category_id?: string | null;
        };
      };
      negotiation_terms: {
        Row: {
          id: string;
          deal_id: string;
          category_id: string;
          term_key: string;
          term_label: string;
          term_description: string | null;
          source_facility_id: string | null;
          source_clause_reference: string | null;
          value_type: 'text' | 'number' | 'percentage' | 'currency_amount' | 'date' | 'boolean' | 'selection' | 'multi_select' | 'table' | 'rich_text';
          allowed_values: Json | null;
          current_value: Json | null;
          current_value_text: string | null;
          negotiation_status: 'not_started' | 'proposed' | 'under_discussion' | 'pending_approval' | 'agreed' | 'locked';
          is_locked: boolean;
          locked_by: string | null;
          locked_at: string | null;
          lock_reason: string | null;
          depends_on: string[] | null;
          impacts: string[] | null;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          deal_id: string;
          category_id: string;
          term_key: string;
          term_label: string;
          term_description?: string | null;
          source_facility_id?: string | null;
          source_clause_reference?: string | null;
          value_type: 'text' | 'number' | 'percentage' | 'currency_amount' | 'date' | 'boolean' | 'selection' | 'multi_select' | 'table' | 'rich_text';
          allowed_values?: Json | null;
          current_value?: Json | null;
          current_value_text?: string | null;
          negotiation_status?: 'not_started' | 'proposed' | 'under_discussion' | 'pending_approval' | 'agreed' | 'locked';
          is_locked?: boolean;
          locked_by?: string | null;
          locked_at?: string | null;
          lock_reason?: string | null;
          depends_on?: string[] | null;
          impacts?: string[] | null;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          deal_id?: string;
          category_id?: string;
          term_key?: string;
          term_label?: string;
          term_description?: string | null;
          source_facility_id?: string | null;
          source_clause_reference?: string | null;
          value_type?: 'text' | 'number' | 'percentage' | 'currency_amount' | 'date' | 'boolean' | 'selection' | 'multi_select' | 'table' | 'rich_text';
          allowed_values?: Json | null;
          current_value?: Json | null;
          current_value_text?: string | null;
          negotiation_status?: 'not_started' | 'proposed' | 'under_discussion' | 'pending_approval' | 'agreed' | 'locked';
          is_locked?: boolean;
          locked_by?: string | null;
          locked_at?: string | null;
          lock_reason?: string | null;
          depends_on?: string[] | null;
          impacts?: string[] | null;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      term_proposals: {
        Row: {
          id: string;
          term_id: string;
          deal_id: string;
          proposed_by: string;
          proposed_by_party: string;
          proposed_at: string;
          proposed_value: Json;
          proposed_value_text: string | null;
          rationale: string | null;
          status: 'pending' | 'accepted' | 'rejected' | 'superseded' | 'withdrawn';
          responses: Json | null;
          resolved_at: string | null;
          resolved_by: string | null;
          resolution_note: string | null;
        };
        Insert: {
          id?: string;
          term_id: string;
          deal_id: string;
          proposed_by: string;
          proposed_by_party: string;
          proposed_at?: string;
          proposed_value: Json;
          proposed_value_text?: string | null;
          rationale?: string | null;
          status?: 'pending' | 'accepted' | 'rejected' | 'superseded' | 'withdrawn';
          responses?: Json | null;
          resolved_at?: string | null;
          resolved_by?: string | null;
          resolution_note?: string | null;
        };
        Update: {
          id?: string;
          term_id?: string;
          deal_id?: string;
          proposed_by?: string;
          proposed_by_party?: string;
          proposed_at?: string;
          proposed_value?: Json;
          proposed_value_text?: string | null;
          rationale?: string | null;
          status?: 'pending' | 'accepted' | 'rejected' | 'superseded' | 'withdrawn';
          responses?: Json | null;
          resolved_at?: string | null;
          resolved_by?: string | null;
          resolution_note?: string | null;
        };
      };
      term_comments: {
        Row: {
          id: string;
          term_id: string;
          deal_id: string;
          proposal_id: string | null;
          author_id: string;
          author_party: string;
          content: string;
          parent_comment_id: string | null;
          is_resolved: boolean;
          resolved_by: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          term_id: string;
          deal_id: string;
          proposal_id?: string | null;
          author_id: string;
          author_party: string;
          content: string;
          parent_comment_id?: string | null;
          is_resolved?: boolean;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          term_id?: string;
          deal_id?: string;
          proposal_id?: string | null;
          author_id?: string;
          author_party?: string;
          content?: string;
          parent_comment_id?: string | null;
          is_resolved?: boolean;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      term_history: {
        Row: {
          id: string;
          term_id: string;
          deal_id: string;
          change_type: 'created' | 'value_changed' | 'status_changed' | 'locked' | 'unlocked' | 'proposal_accepted' | 'proposal_rejected';
          previous_value: Json | null;
          new_value: Json | null;
          previous_status: string | null;
          new_status: string | null;
          changed_by: string;
          changed_by_party: string;
          changed_at: string;
          change_note: string | null;
          related_proposal_id: string | null;
        };
        Insert: {
          id?: string;
          term_id: string;
          deal_id: string;
          change_type: 'created' | 'value_changed' | 'status_changed' | 'locked' | 'unlocked' | 'proposal_accepted' | 'proposal_rejected';
          previous_value?: Json | null;
          new_value?: Json | null;
          previous_status?: string | null;
          new_status?: string | null;
          changed_by: string;
          changed_by_party: string;
          changed_at?: string;
          change_note?: string | null;
          related_proposal_id?: string | null;
        };
        Update: {
          id?: string;
          term_id?: string;
          deal_id?: string;
          change_type?: 'created' | 'value_changed' | 'status_changed' | 'locked' | 'unlocked' | 'proposal_accepted' | 'proposal_rejected';
          previous_value?: Json | null;
          new_value?: Json | null;
          previous_status?: string | null;
          new_status?: string | null;
          changed_by?: string;
          changed_by_party?: string;
          changed_at?: string;
          change_note?: string | null;
          related_proposal_id?: string | null;
        };
      };
      deal_activities: {
        Row: {
          id: string;
          deal_id: string;
          activity_type: 'deal_created' | 'participant_joined' | 'participant_removed' | 'term_proposed' | 'term_agreed' | 'term_locked' | 'comment_added' | 'document_exported' | 'status_changed';
          actor_id: string;
          actor_party: string;
          term_id: string | null;
          proposal_id: string | null;
          comment_id: string | null;
          details: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          deal_id: string;
          activity_type: 'deal_created' | 'participant_joined' | 'participant_removed' | 'term_proposed' | 'term_agreed' | 'term_locked' | 'comment_added' | 'document_exported' | 'status_changed';
          actor_id: string;
          actor_party: string;
          term_id?: string | null;
          proposal_id?: string | null;
          comment_id?: string | null;
          details?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          deal_id?: string;
          activity_type?: 'deal_created' | 'participant_joined' | 'participant_removed' | 'term_proposed' | 'term_agreed' | 'term_locked' | 'comment_added' | 'document_exported' | 'status_changed';
          actor_id?: string;
          actor_party?: string;
          term_id?: string | null;
          proposal_id?: string | null;
          comment_id?: string | null;
          details?: Json | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
};

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];

// Convenient type aliases - Module 1: Document Intelligence Hub
export type Organization = Tables<'organizations'>;
export type User = Tables<'users'>;
export type LoanDocument = Tables<'loan_documents'>;
export type LoanFacility = Tables<'loan_facilities'>;
export type FinancialCovenant = Tables<'financial_covenants'>;
export type ReportingObligation = Tables<'reporting_obligations'>;
export type EventOfDefault = Tables<'events_of_default'>;
export type ESGProvision = Tables<'esg_provisions'>;
export type DefinedTerm = Tables<'defined_terms'>;
export type Notification = Tables<'notifications'>;
export type Activity = Tables<'activities'>;

// Module 2: Deal Room & Negotiation Accelerator
export type Deal = Tables<'deals'>;
export type DealParticipant = Tables<'deal_participants'>;
export type TermCategory = Tables<'term_categories'>;
export type NegotiationTerm = Tables<'negotiation_terms'>;
export type TermProposal = Tables<'term_proposals'>;
export type TermComment = Tables<'term_comments'>;
export type TermHistory = Tables<'term_history'>;
export type DealActivity = Tables<'deal_activities'>;
