import type {
  HeadroomListing,
  HeadroomTrade,
  TradeMatchRecommendation,
  PortfolioOptimizationAnalysis,
  HeadroomMarketStats,
  UserExchangeDashboard,
} from './types';

export const mockHeadroomListings: HeadroomListing[] = [
  {
    id: 'listing-1',
    covenant_id: '5',
    covenant_name: 'Minimum Liquidity',
    covenant_type: 'minimum_liquidity',
    facility_id: '4',
    facility_name: 'Neptune Holdings TL',
    borrower_name: 'Neptune Holdings Inc',
    current_headroom_percentage: 68.0,
    current_headroom_absolute: 17000000,
    available_for_trade_percentage: 40.0, // Willing to trade 40% of their 68%
    available_for_trade_absolute: 10000000,
    current_threshold: 25000000,
    current_value: 42000000,
    threshold_type: 'minimum',
    seeking_exchange_types: ['pricing_adjustment', 'fee_sharing', 'cross_guarantee'],
    minimum_trade_size: 5.0,
    borrower_risk_tier: 'low',
    facility_credit_rating: 'BBB+',
    industry_sector: 'healthcare',
    listing_status: 'active',
    listed_date: '2024-12-01T09:00:00Z',
    expires_date: '2025-01-01T00:00:00Z',
  },
  {
    id: 'listing-2',
    covenant_id: '1',
    covenant_name: 'Leverage Ratio',
    covenant_type: 'leverage_ratio',
    facility_id: '1',
    facility_name: 'ABC Holdings - Term Loan A',
    borrower_name: 'ABC Holdings LLC',
    current_headroom_percentage: 20.0,
    current_headroom_absolute: 0.8,
    available_for_trade_percentage: 10.0,
    available_for_trade_absolute: 0.4,
    current_threshold: 4.0,
    current_value: 3.2,
    threshold_type: 'maximum',
    seeking_exchange_types: ['pricing_adjustment', 'shared_covenant'],
    minimum_trade_size: 3.0,
    borrower_risk_tier: 'medium',
    facility_credit_rating: 'BB+',
    industry_sector: 'manufacturing',
    listing_status: 'active',
    listed_date: '2024-12-05T14:00:00Z',
    expires_date: '2024-12-31T00:00:00Z',
  },
  {
    id: 'listing-3',
    covenant_id: '2',
    covenant_name: 'Interest Coverage Ratio',
    covenant_type: 'interest_coverage',
    facility_id: '1',
    facility_name: 'ABC Holdings - Term Loan A',
    borrower_name: 'ABC Holdings LLC',
    current_headroom_percentage: 52.0,
    current_headroom_absolute: 1.3,
    available_for_trade_percentage: 25.0,
    available_for_trade_absolute: 0.65,
    current_threshold: 2.5,
    current_value: 3.8,
    threshold_type: 'minimum',
    seeking_exchange_types: ['cross_guarantee', 'fee_sharing'],
    minimum_trade_size: 5.0,
    borrower_risk_tier: 'medium',
    facility_credit_rating: 'BB+',
    industry_sector: 'manufacturing',
    listing_status: 'active',
    listed_date: '2024-12-03T11:00:00Z',
    expires_date: '2025-01-15T00:00:00Z',
  },
];

export const mockTrades: HeadroomTrade[] = [
  {
    id: 'trade-1',
    offering_listing_id: 'listing-1',
    offering_covenant_id: '5',
    offering_covenant_name: 'Minimum Liquidity',
    offering_facility_name: 'Neptune Holdings TL',
    offering_borrower_name: 'Neptune Holdings Inc',
    offering_headroom_percentage: 68.0,
    receiving_covenant_id: '3',
    receiving_covenant_name: 'Leverage Ratio',
    receiving_facility_name: 'XYZ Corp Revolver',
    receiving_borrower_name: 'XYZ Corporation',
    receiving_headroom_percentage: 11.4,
    headroom_amount_traded: 15.0,
    exchange_type: 'pricing_adjustment',
    exchange_details: {
      type: 'pricing_adjustment',
      pricing_adjustment: {
        basis_points_reduction: 25,
        duration_months: 12,
        estimated_value_usd: 87500,
      },
    },
    compatibility_score: 87,
    fair_value_score: 92,
    risk_adjusted_score: 85,
    status: 'negotiating',
    proposed_date: '2024-12-07T10:30:00Z',
    accepted_date: null,
    executed_date: null,
    expires_date: '2024-12-21T10:30:00Z',
    proposed_by: 'system',
  },
  {
    id: 'trade-2',
    offering_listing_id: 'listing-2',
    offering_covenant_id: '1',
    offering_covenant_name: 'Leverage Ratio',
    offering_facility_name: 'ABC Holdings - Term Loan A',
    offering_borrower_name: 'ABC Holdings LLC',
    offering_headroom_percentage: 20.0,
    receiving_covenant_id: '4',
    receiving_covenant_name: 'Fixed Charge Coverage',
    receiving_facility_name: 'Delta Manufacturing TL',
    receiving_borrower_name: 'Delta Manufacturing Co',
    receiving_headroom_percentage: -12.5,
    headroom_amount_traded: 8.0,
    exchange_type: 'cross_guarantee',
    exchange_details: {
      type: 'cross_guarantee',
      cross_guarantee: {
        guarantee_amount_usd: 5000000,
        guarantee_percentage: 6.67,
        guarantee_duration_months: 18,
        guarantee_conditions: [
          'Guarantee triggers if FCCR falls below 1.0x',
          'Limited to principal repayment only',
          'Released upon successful waiver extension or covenant cure',
        ],
      },
    },
    compatibility_score: 73,
    fair_value_score: 78,
    risk_adjusted_score: 65,
    status: 'proposed',
    proposed_date: '2024-12-08T14:15:00Z',
    accepted_date: null,
    executed_date: null,
    expires_date: '2024-12-22T14:15:00Z',
    proposed_by: 'receiving_party',
  },
  {
    id: 'trade-3',
    offering_listing_id: 'listing-3',
    offering_covenant_id: '2',
    offering_covenant_name: 'Interest Coverage Ratio',
    offering_facility_name: 'ABC Holdings - Term Loan A',
    offering_borrower_name: 'ABC Holdings LLC',
    offering_headroom_percentage: 52.0,
    receiving_covenant_id: '3',
    receiving_covenant_name: 'Leverage Ratio',
    receiving_facility_name: 'XYZ Corp Revolver',
    receiving_borrower_name: 'XYZ Corporation',
    receiving_headroom_percentage: 11.4,
    headroom_amount_traded: 12.0,
    exchange_type: 'fee_sharing',
    exchange_details: {
      type: 'fee_sharing',
      fee_sharing: {
        annual_fee_reduction_usd: 45000,
        commitment_fee_reduction_bps: 15,
        duration_months: 24,
      },
    },
    compatibility_score: 81,
    fair_value_score: 85,
    risk_adjusted_score: 79,
    status: 'accepted',
    proposed_date: '2024-12-06T09:00:00Z',
    accepted_date: '2024-12-07T16:30:00Z',
    executed_date: null,
    expires_date: '2024-12-20T09:00:00Z',
    proposed_by: 'offering_party',
  },
];

export const mockTradeRecommendations: TradeMatchRecommendation[] = [
  {
    id: 'rec-1',
    listing_id: 'listing-1',
    matched_covenant_id: '3',
    matched_covenant_name: 'Leverage Ratio',
    matched_facility_name: 'XYZ Corp Revolver',
    matched_borrower_name: 'XYZ Corporation',
    matched_headroom_percentage: 11.4,
    compatibility_score: 87,
    risk_compatibility: 82,
    covenant_compatibility: 90,
    timing_compatibility: 89,
    recommended_exchange_type: 'pricing_adjustment',
    recommended_exchange_terms: {
      type: 'pricing_adjustment',
      pricing_adjustment: {
        basis_points_reduction: 25,
        duration_months: 12,
        estimated_value_usd: 87500,
      },
    },
    fair_exchange_rate: 1.67,
    value_to_offering_party: 87500,
    value_to_receiving_party: 105000,
    mutual_benefit_score: 88,
    match_rationale:
      'Neptune Holdings has exceptional liquidity headroom (68%) while XYZ Corp is approaching leverage covenant stress (11.4% headroom). Both facilities are in similar credit quality tiers and have quarterly test frequencies that align well.',
    risk_assessment:
      'Low risk trade. Neptune Holdings maintains strong financial position even after headroom transfer. XYZ Corp benefits significantly from additional cushion during declining trend. Compatible industries and credit profiles reduce cross-contamination risk.',
    recommendation_summary:
      'STRONG MATCH: Trade 15% liquidity headroom for 25bps pricing reduction over 12 months. Creates $87.5K value for Neptune and provides critical breathing room for XYZ Corp.',
    generated_date: '2024-12-08T08:00:00Z',
  },
  {
    id: 'rec-2',
    listing_id: 'listing-3',
    matched_covenant_id: '6',
    matched_covenant_name: 'Interest Coverage',
    matched_facility_name: 'Sigma Holdings ABL',
    matched_borrower_name: 'Sigma Holdings Inc',
    matched_headroom_percentage: -30.0,
    compatibility_score: 62,
    risk_compatibility: 45,
    covenant_compatibility: 85,
    timing_compatibility: 70,
    recommended_exchange_type: 'hybrid',
    recommended_exchange_terms: {
      type: 'hybrid',
      hybrid: {
        components: ['cross_guarantee', 'pricing_adjustment'],
        component_weights: [60, 40],
      },
      cross_guarantee: {
        guarantee_amount_usd: 8000000,
        guarantee_percentage: 16.0,
        guarantee_duration_months: 12,
        guarantee_conditions: [
          'Guarantee triggers if IC ratio remains below 1.5x for 2 consecutive quarters',
          'ABC Holdings provides backup guarantee for interest payments only',
          'Released upon successful restructuring or facility paydown',
        ],
      },
      pricing_adjustment: {
        basis_points_reduction: 50,
        duration_months: 12,
        estimated_value_usd: 62500,
      },
    },
    fair_exchange_rate: 2.8,
    value_to_offering_party: 125000,
    value_to_receiving_party: 350000,
    mutual_benefit_score: 68,
    match_rationale:
      'High-risk but high-value trade. ABC Holdings has strong interest coverage headroom (52%) while Sigma Holdings is in severe breach (-30%). Covenant types are compatible but risk profiles diverge significantly.',
    risk_assessment:
      'ELEVATED RISK: Sigma Holdings is in critical status. This trade requires substantial risk premium through hybrid structure. Cross-guarantee must be carefully structured with clear triggers. ABC Holdings takes on workout exposure but receives significant compensation.',
    recommendation_summary:
      'MODERATE MATCH: Complex hybrid trade combining cross-guarantee ($8M, 16% of facility) plus 50bps pricing reduction. High risk requires substantial premium. Recommend enhanced monitoring and clear exit triggers.',
    generated_date: '2024-12-08T08:00:00Z',
  },
  {
    id: 'rec-3',
    listing_id: 'listing-2',
    matched_covenant_id: '4',
    matched_covenant_name: 'Fixed Charge Coverage',
    matched_facility_name: 'Delta Manufacturing TL',
    matched_borrower_name: 'Delta Manufacturing Co',
    matched_headroom_percentage: -12.5,
    compatibility_score: 73,
    risk_compatibility: 75,
    covenant_compatibility: 68,
    timing_compatibility: 77,
    recommended_exchange_type: 'shared_covenant',
    recommended_exchange_terms: {
      type: 'shared_covenant',
      shared_covenant: {
        new_shared_threshold: 3.6,
        pooled_calculation: true,
        shared_liability_percentage: 50,
      },
    },
    fair_exchange_rate: 1.25,
    value_to_offering_party: 95000,
    value_to_receiving_party: 180000,
    mutual_benefit_score: 76,
    match_rationale:
      'Same borrower (ABC Holdings LLC) across two different facilities creates unique opportunity for shared covenant structure. Leverage Ratio facility has healthy headroom while FCCR facility is in waiver. Both manufacturing sector, compatible maturity profiles.',
    risk_assessment:
      'Moderate risk with strong upside. Both facilities share same ultimate borrower, reducing complexity. Waiver period provides window for restructuring. Shared covenant pool reduces individual facility stress while maintaining overall credit protection.',
    recommendation_summary:
      'GOOD MATCH: Create pooled covenant structure combining Leverage and FCCR calculations. Share 8% headroom from leverage covenant to support FCCR covenant cure. Benefits both facilities under same borrower umbrella.',
    generated_date: '2024-12-08T08:00:00Z',
  },
];

export const mockPortfolioOptimization: PortfolioOptimizationAnalysis = {
  portfolio_id: 'portfolio-main',
  analysis_date: '2024-12-08T08:00:00Z',
  total_facilities: 5,
  total_covenants: 6,
  covenants_at_risk: 3,
  average_headroom_percentage: 18.2,
  total_excess_headroom: 140.0, // Sum of headroom above 30%: (68-30) + (52-30) + (20-30 doesn't count)
  total_deficit_headroom: 53.9, // Sum of headroom below 15%: (11.4-15) + (12.5+15) + (30+15)
  optimization_opportunity_score: 78,
  recommended_trades: mockTradeRecommendations,
  potential_breach_prevention: 2,
  estimated_total_value_created: 307500,
  portfolio_breach_probability_current: 42.5,
  portfolio_breach_probability_optimized: 18.3,
  risk_reduction_percentage: 56.9,
  summary:
    'Portfolio analysis reveals significant optimization opportunity with 140% excess headroom concentrated in 2 covenants while 3 covenants face deficit/breach risk. Recommended trades can reduce portfolio-wide breach probability from 42.5% to 18.3% while creating $307.5K in estimated value through efficient capital reallocation.',
  top_priorities: [
    'Trade Neptune Holdings liquidity headroom (68%) to support XYZ Corp leverage covenant (11.4%)',
    'Create shared covenant structure for ABC Holdings facilities to cure FCCR breach',
    'Consider hybrid structure for Sigma Holdings despite elevated risk',
  ],
};

export const mockMarketStats: HeadroomMarketStats = {
  total_active_listings: 3,
  total_facilities_participating: 4,
  average_excess_headroom: 46.7,
  average_deficit_headroom: -10.4,
  trades_completed_30d: 7,
  trades_in_negotiation: 2,
  total_value_exchanged_30d: 425000,
  most_common_exchange_type: 'pricing_adjustment',
  exchange_type_distribution: {
    pricing_adjustment: 5,
    cross_guarantee: 3,
    shared_covenant: 2,
    fee_sharing: 2,
    hybrid: 1,
  },
  most_traded_covenant_types: [
    {
      covenant_type: 'leverage_ratio',
      trade_count: 6,
      average_headroom_traded: 12.3,
    },
    {
      covenant_type: 'interest_coverage',
      trade_count: 4,
      average_headroom_traded: 15.8,
    },
    {
      covenant_type: 'minimum_liquidity',
      trade_count: 3,
      average_headroom_traded: 22.5,
    },
  ],
  last_updated: '2024-12-08T08:00:00Z',
};

export const mockUserDashboard: UserExchangeDashboard = {
  active_listings: mockHeadroomListings,
  incoming_proposals: mockTrades.filter((t) => t.proposed_by !== 'offering_party'),
  outgoing_proposals: mockTrades.filter((t) => t.proposed_by === 'offering_party'),
  active_trades: mockTrades.filter((t) => t.status === 'accepted' || t.status === 'executed'),
  recommended_matches: mockTradeRecommendations,
  total_value_received: 187500,
  total_value_given: 95000,
  trades_completed_count: 4,
};
