// Export Types and Configuration for Document Comparison
// Supports PDF, Word (DOCX), and Excel exports with annotations preserved

import type { ComparisonResult } from '@/types';
import type { ComparisonRiskAnalysis, ComparisonChange, ComparisonCategory } from '../../lib/types';
import type { Annotation, ReviewStatus, User, AnnotationsMap } from './types';

// ============================================
// Export Format Types
// ============================================

/**
 * Supported export formats
 */
export type ExportFormat = 'pdf' | 'docx' | 'xlsx';

/**
 * Export template type for different audiences
 */
export type ExportTemplateType =
  | 'executive_summary'     // High-level summary for leadership/board
  | 'legal_redline'         // Detailed redline document for legal review
  | 'audit_changelog'       // Complete audit trail for compliance
  | 'standard'              // Standard comparison report
  | 'custom';               // User-configured template

/**
 * Content sections that can be included/excluded
 */
export type ExportSection =
  | 'executive_summary'
  | 'document_metadata'
  | 'risk_analysis'
  | 'market_benchmarks'
  | 'changes_by_category'
  | 'annotations'
  | 'comments'
  | 'review_status'
  | 'impact_analysis'
  | 'change_statistics'
  | 'audit_trail'
  | 'appendix';

// ============================================
// Export Configuration
// ============================================

/**
 * Configuration for which sections to include in export
 */
export interface ExportSectionConfig {
  /** Section identifier */
  section: ExportSection;
  /** Whether to include this section */
  included: boolean;
  /** Display order (lower = earlier) */
  order: number;
}

/**
 * Styling options for PDF/DOCX exports
 */
export interface ExportStylingOptions {
  /** Include company logo */
  includeLogo: boolean;
  /** Logo URL if included */
  logoUrl?: string;
  /** Primary brand color (hex) */
  primaryColor: string;
  /** Include page numbers */
  includePageNumbers: boolean;
  /** Include table of contents */
  includeTableOfContents: boolean;
  /** Include watermark */
  includeWatermark: boolean;
  /** Watermark text */
  watermarkText?: string;
  /** Font family */
  fontFamily: 'inter' | 'arial' | 'times' | 'helvetica';
  /** Base font size */
  fontSize: number;
}

/**
 * Filter options for what changes to include
 */
export interface ExportFilterOptions {
  /** Include added changes */
  includeAdded: boolean;
  /** Include removed changes */
  includeRemoved: boolean;
  /** Include modified changes */
  includeModified: boolean;
  /** Filter by review status */
  reviewStatuses: ReviewStatus[] | 'all';
  /** Minimum risk score (1-10) to include, null for all */
  minRiskScore: number | null;
  /** Categories to include */
  categories: string[] | 'all';
  /** Only include changes with annotations */
  annotatedOnly: boolean;
  /** Only include changes with comments */
  withCommentsOnly: boolean;
}

/**
 * Main export configuration
 */
export interface ExportConfig {
  /** Export format */
  format: ExportFormat;
  /** Template type */
  template: ExportTemplateType;
  /** Custom template name if template is 'custom' */
  customTemplateName?: string;
  /** Filename (without extension) */
  filename: string;
  /** Sections to include */
  sections: ExportSectionConfig[];
  /** Styling options */
  styling: ExportStylingOptions;
  /** Filter options */
  filters: ExportFilterOptions;
  /** Include risk scores if available */
  includeRiskScores: boolean;
  /** Include market benchmarks if available */
  includeMarketBenchmarks: boolean;
  /** Generated by user info */
  generatedBy?: {
    name: string;
    email: string;
  };
  /** Additional notes to include */
  notes?: string;
}

// ============================================
// Export Data Structures
// ============================================

/**
 * Enriched change with annotation and risk data for export
 */
export interface ExportableChange {
  /** Original change data */
  change: ComparisonChange;
  /** Category this change belongs to */
  category: string;
  /** Unique change ID */
  changeId: string;
  /** Annotation if exists */
  annotation?: Annotation;
  /** Risk score if available */
  riskScore?: {
    severityScore: number;
    severity: 'low' | 'medium' | 'high' | 'critical';
    favoredParty: 'borrower' | 'lender' | 'neutral';
    riskAnalysis: string;
  };
  /** Market benchmark if available */
  marketBenchmark?: {
    marketRangeLow: string;
    marketRangeHigh: string;
    marketMedian: string;
    marketPosition: 'below_market' | 'at_market' | 'above_market';
    percentile: number;
  };
}

/**
 * Category with enriched changes for export
 */
export interface ExportableCategory {
  /** Category name */
  category: string;
  /** Enriched changes */
  changes: ExportableChange[];
  /** Category risk summary if available */
  riskSummary?: {
    averageSeverityScore: number;
    borrowerFavoredCount: number;
    lenderFavoredCount: number;
    neutralCount: number;
  };
}

/**
 * Complete export data package
 */
export interface ExportData {
  /** Export configuration used */
  config: ExportConfig;
  /** Document metadata */
  metadata: {
    document1: {
      id: string;
      name: string;
    };
    document2: {
      id: string;
      name: string;
    };
    comparedAt: string;
    exportedAt: string;
    exportedBy?: {
      name: string;
      email: string;
    };
  };
  /** Executive summary text */
  executiveSummary?: string;
  /** Impact analysis text */
  impactAnalysis: string;
  /** Statistics */
  statistics: {
    totalChanges: number;
    addedCount: number;
    removedCount: number;
    modifiedCount: number;
    categoriesCount: number;
    annotatedCount: number;
    reviewedCount: number;
    flaggedCount: number;
    requiresLegalCount: number;
    pendingCount: number;
  };
  /** Risk analysis summary if available */
  riskAnalysisSummary?: {
    overallRiskScore: number;
    overallSeverity: 'low' | 'medium' | 'high' | 'critical';
    overallDirection: 'borrower_favorable' | 'lender_favorable' | 'balanced';
    highRiskCount: number;
    keyFindings: string[];
    executiveSummary: string;
  };
  /** Categories with enriched changes */
  categories: ExportableCategory[];
  /** Audit trail entries */
  auditTrail?: AuditTrailEntry[];
}

/**
 * Audit trail entry for compliance exports
 */
export interface AuditTrailEntry {
  /** Timestamp of the action */
  timestamp: string;
  /** User who performed the action */
  user: {
    name: string;
    email: string;
  };
  /** Action type */
  action: 'comparison_created' | 'annotation_added' | 'status_changed' | 'comment_added' | 'export_generated';
  /** Description of the action */
  description: string;
  /** Related change ID if applicable */
  changeId?: string;
  /** Previous value if changed */
  previousValue?: string;
  /** New value if changed */
  newValue?: string;
}

// ============================================
// Export Templates
// ============================================

/**
 * Predefined export template
 */
export interface ExportTemplate {
  /** Template identifier */
  id: string;
  /** Template type */
  type: ExportTemplateType;
  /** Display name */
  name: string;
  /** Description */
  description: string;
  /** Supported formats for this template */
  supportedFormats: ExportFormat[];
  /** Default sections configuration */
  defaultSections: ExportSectionConfig[];
  /** Default styling */
  defaultStyling: ExportStylingOptions;
  /** Default filters */
  defaultFilters: ExportFilterOptions;
  /** Whether to include risk scores by default */
  includeRiskScores: boolean;
  /** Whether to include market benchmarks by default */
  includeMarketBenchmarks: boolean;
}

/**
 * Predefined export templates
 */
export const EXPORT_TEMPLATES: ExportTemplate[] = [
  {
    id: 'executive-summary',
    type: 'executive_summary',
    name: 'Executive Summary',
    description: 'High-level summary with key findings for leadership and board presentations',
    supportedFormats: ['pdf', 'docx'],
    defaultSections: [
      { section: 'executive_summary', included: true, order: 1 },
      { section: 'document_metadata', included: true, order: 2 },
      { section: 'risk_analysis', included: true, order: 3 },
      { section: 'change_statistics', included: true, order: 4 },
      { section: 'impact_analysis', included: true, order: 5 },
    ],
    defaultStyling: {
      includeLogo: true,
      primaryColor: '#2563eb',
      includePageNumbers: true,
      includeTableOfContents: false,
      includeWatermark: false,
      fontFamily: 'inter',
      fontSize: 11,
    },
    defaultFilters: {
      includeAdded: true,
      includeRemoved: true,
      includeModified: true,
      reviewStatuses: 'all',
      minRiskScore: 7, // Only high-risk items
      categories: 'all',
      annotatedOnly: false,
      withCommentsOnly: false,
    },
    includeRiskScores: true,
    includeMarketBenchmarks: false,
  },
  {
    id: 'legal-redline',
    type: 'legal_redline',
    name: 'Legal Redline',
    description: 'Detailed redline document with all changes, annotations, and comments for legal review',
    supportedFormats: ['pdf', 'docx'],
    defaultSections: [
      { section: 'document_metadata', included: true, order: 1 },
      { section: 'executive_summary', included: true, order: 2 },
      { section: 'changes_by_category', included: true, order: 3 },
      { section: 'annotations', included: true, order: 4 },
      { section: 'comments', included: true, order: 5 },
      { section: 'review_status', included: true, order: 6 },
      { section: 'impact_analysis', included: true, order: 7 },
      { section: 'appendix', included: true, order: 8 },
    ],
    defaultStyling: {
      includeLogo: true,
      primaryColor: '#7c3aed',
      includePageNumbers: true,
      includeTableOfContents: true,
      includeWatermark: true,
      watermarkText: 'DRAFT - FOR LEGAL REVIEW',
      fontFamily: 'times',
      fontSize: 11,
    },
    defaultFilters: {
      includeAdded: true,
      includeRemoved: true,
      includeModified: true,
      reviewStatuses: 'all',
      minRiskScore: null,
      categories: 'all',
      annotatedOnly: false,
      withCommentsOnly: false,
    },
    includeRiskScores: true,
    includeMarketBenchmarks: true,
  },
  {
    id: 'audit-changelog',
    type: 'audit_changelog',
    name: 'Audit Change Log',
    description: 'Complete audit-ready change log with timestamps and review trail for compliance',
    supportedFormats: ['pdf', 'xlsx'],
    defaultSections: [
      { section: 'document_metadata', included: true, order: 1 },
      { section: 'change_statistics', included: true, order: 2 },
      { section: 'changes_by_category', included: true, order: 3 },
      { section: 'review_status', included: true, order: 4 },
      { section: 'audit_trail', included: true, order: 5 },
      { section: 'annotations', included: true, order: 6 },
      { section: 'comments', included: true, order: 7 },
    ],
    defaultStyling: {
      includeLogo: true,
      primaryColor: '#059669',
      includePageNumbers: true,
      includeTableOfContents: true,
      includeWatermark: true,
      watermarkText: 'CONFIDENTIAL - AUDIT DOCUMENT',
      fontFamily: 'arial',
      fontSize: 10,
    },
    defaultFilters: {
      includeAdded: true,
      includeRemoved: true,
      includeModified: true,
      reviewStatuses: 'all',
      minRiskScore: null,
      categories: 'all',
      annotatedOnly: false,
      withCommentsOnly: false,
    },
    includeRiskScores: true,
    includeMarketBenchmarks: false,
  },
  {
    id: 'standard',
    type: 'standard',
    name: 'Standard Report',
    description: 'Standard comparison report with all changes and analysis',
    supportedFormats: ['pdf', 'docx', 'xlsx'],
    defaultSections: [
      { section: 'document_metadata', included: true, order: 1 },
      { section: 'executive_summary', included: true, order: 2 },
      { section: 'change_statistics', included: true, order: 3 },
      { section: 'risk_analysis', included: true, order: 4 },
      { section: 'changes_by_category', included: true, order: 5 },
      { section: 'impact_analysis', included: true, order: 6 },
    ],
    defaultStyling: {
      includeLogo: false,
      primaryColor: '#3b82f6',
      includePageNumbers: true,
      includeTableOfContents: false,
      includeWatermark: false,
      fontFamily: 'inter',
      fontSize: 11,
    },
    defaultFilters: {
      includeAdded: true,
      includeRemoved: true,
      includeModified: true,
      reviewStatuses: 'all',
      minRiskScore: null,
      categories: 'all',
      annotatedOnly: false,
      withCommentsOnly: false,
    },
    includeRiskScores: true,
    includeMarketBenchmarks: true,
  },
];

// ============================================
// Default Configurations
// ============================================

/**
 * Default export styling
 */
export const DEFAULT_EXPORT_STYLING: ExportStylingOptions = {
  includeLogo: false,
  primaryColor: '#3b82f6',
  includePageNumbers: true,
  includeTableOfContents: false,
  includeWatermark: false,
  fontFamily: 'inter',
  fontSize: 11,
};

/**
 * Default export filters
 */
export const DEFAULT_EXPORT_FILTERS: ExportFilterOptions = {
  includeAdded: true,
  includeRemoved: true,
  includeModified: true,
  reviewStatuses: 'all',
  minRiskScore: null,
  categories: 'all',
  annotatedOnly: false,
  withCommentsOnly: false,
};

/**
 * All sections in default order
 */
export const ALL_EXPORT_SECTIONS: ExportSectionConfig[] = [
  { section: 'document_metadata', included: true, order: 1 },
  { section: 'executive_summary', included: true, order: 2 },
  { section: 'change_statistics', included: true, order: 3 },
  { section: 'risk_analysis', included: true, order: 4 },
  { section: 'market_benchmarks', included: true, order: 5 },
  { section: 'impact_analysis', included: true, order: 6 },
  { section: 'changes_by_category', included: true, order: 7 },
  { section: 'annotations', included: true, order: 8 },
  { section: 'comments', included: true, order: 9 },
  { section: 'review_status', included: true, order: 10 },
  { section: 'audit_trail', included: false, order: 11 },
  { section: 'appendix', included: false, order: 12 },
];

/**
 * Section display names
 */
export const SECTION_DISPLAY_NAMES: Record<ExportSection, string> = {
  executive_summary: 'Executive Summary',
  document_metadata: 'Document Metadata',
  risk_analysis: 'Risk Analysis',
  market_benchmarks: 'Market Benchmarks',
  changes_by_category: 'Changes by Category',
  annotations: 'Annotations',
  comments: 'Comments',
  review_status: 'Review Status',
  impact_analysis: 'Impact Analysis',
  change_statistics: 'Change Statistics',
  audit_trail: 'Audit Trail',
  appendix: 'Appendix',
};

/**
 * Format display names and metadata
 */
export const FORMAT_CONFIG: Record<ExportFormat, {
  name: string;
  extension: string;
  mimeType: string;
  icon: string;
  description: string;
}> = {
  pdf: {
    name: 'PDF Document',
    extension: 'pdf',
    mimeType: 'application/pdf',
    icon: 'FileText',
    description: 'Best for sharing and printing',
  },
  docx: {
    name: 'Word Document',
    extension: 'docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    icon: 'FileText',
    description: 'Best for editing and collaboration',
  },
  xlsx: {
    name: 'Excel Spreadsheet',
    extension: 'xlsx',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    icon: 'Table',
    description: 'Best for data analysis and filtering',
  },
};

// ============================================
// Helper Functions
// ============================================

/**
 * Get template by ID
 */
export function getExportTemplate(templateId: string): ExportTemplate | undefined {
  return EXPORT_TEMPLATES.find((t) => t.id === templateId);
}

/**
 * Get template by type
 */
export function getExportTemplateByType(type: ExportTemplateType): ExportTemplate | undefined {
  return EXPORT_TEMPLATES.find((t) => t.type === type);
}

/**
 * Create default export config from template
 */
export function createExportConfigFromTemplate(
  template: ExportTemplate,
  format: ExportFormat,
  filename: string
): ExportConfig {
  return {
    format,
    template: template.type,
    filename,
    sections: [...template.defaultSections],
    styling: { ...template.defaultStyling },
    filters: { ...template.defaultFilters },
    includeRiskScores: template.includeRiskScores,
    includeMarketBenchmarks: template.includeMarketBenchmarks,
  };
}

/**
 * Generate default filename for export
 */
export function generateExportFilename(
  doc1Name: string,
  doc2Name: string,
  template: ExportTemplateType,
  format: ExportFormat
): string {
  const sanitize = (name: string) =>
    name.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 20);

  const dateStr = new Date().toISOString().split('T')[0];
  const templateSuffix = template === 'executive_summary' ? 'summary' :
    template === 'legal_redline' ? 'redline' :
    template === 'audit_changelog' ? 'audit' : 'comparison';

  return `${sanitize(doc1Name)}_vs_${sanitize(doc2Name)}_${templateSuffix}_${dateStr}`;
}
