import type { DealWithStats, CategoryWithTerms, DealParticipant } from './types';
import { calculateDeadlineStatsFromCategories } from './deadline-utils';

export const mockDeals: DealWithStats[] = [
  {
    id: '1',
    organization_id: 'org-1',
    created_by: 'user-1',
    deal_name: 'Project Apollo - Term Loan Facility',
    description: 'USD 500M term loan facility for acquisition financing',
    deal_type: 'new_facility',
    status: 'active',
    negotiation_mode: 'collaborative',
    base_facility_id: null,
    target_close_date: '2025-02-15',
    created_at: '2024-12-01T10:00:00Z',
    updated_at: '2024-12-06T15:30:00Z',
    stats: {
      total_terms: 24,
      agreed_terms: 18,
      pending_proposals: 3,
      participant_count: 8,
    },
  },
  {
    id: '2',
    organization_id: 'org-1',
    created_by: 'user-1',
    deal_name: 'XYZ Corp - Amendment No. 2',
    description: 'Covenant modifications and maturity extension',
    deal_type: 'amendment',
    status: 'active',
    negotiation_mode: 'collaborative',
    base_facility_id: 'fac-1',
    target_close_date: '2025-01-31',
    created_at: '2024-11-28T14:00:00Z',
    updated_at: '2024-12-05T09:15:00Z',
    stats: {
      total_terms: 12,
      agreed_terms: 8,
      pending_proposals: 2,
      participant_count: 5,
    },
  },
  {
    id: '3',
    organization_id: 'org-1',
    created_by: 'user-2',
    deal_name: 'Neptune Holdings - Refinancing',
    description: 'Complete refinancing of existing senior secured facilities',
    deal_type: 'refinancing',
    status: 'draft',
    negotiation_mode: 'proposal_based',
    base_facility_id: null,
    target_close_date: '2025-03-30',
    created_at: '2024-12-05T16:00:00Z',
    updated_at: '2024-12-05T16:00:00Z',
    stats: {
      total_terms: 0,
      agreed_terms: 0,
      pending_proposals: 0,
      participant_count: 2,
    },
  },
  {
    id: '4',
    organization_id: 'org-1',
    created_by: 'user-1',
    deal_name: 'Delta Corp - Consent Request',
    description: 'Dividend distribution consent under existing facility',
    deal_type: 'consent',
    status: 'agreed',
    negotiation_mode: 'collaborative',
    base_facility_id: 'fac-2',
    target_close_date: '2024-12-20',
    created_at: '2024-11-15T11:00:00Z',
    updated_at: '2024-12-04T14:30:00Z',
    stats: {
      total_terms: 5,
      agreed_terms: 5,
      pending_proposals: 0,
      participant_count: 4,
    },
  },
  {
    id: '5',
    organization_id: 'org-1',
    created_by: 'user-3',
    deal_name: 'Omega Group - Extension',
    description: 'Two-year maturity extension with repricing',
    deal_type: 'extension',
    status: 'paused',
    negotiation_mode: 'proposal_based',
    base_facility_id: 'fac-3',
    target_close_date: null,
    created_at: '2024-10-20T09:00:00Z',
    updated_at: '2024-11-30T10:00:00Z',
    stats: {
      total_terms: 8,
      agreed_terms: 4,
      pending_proposals: 1,
      participant_count: 6,
    },
  },
];

// Helper to get relative dates for demo purposes
const getRelativeDate = (daysFromNow: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString().split('T')[0];
};

export const mockCategories: CategoryWithTerms[] = [
  {
    id: 'cat-1',
    deal_id: '1',
    name: 'Facility Terms',
    display_order: 1,
    parent_category_id: null,
    created_at: '2024-12-01T10:00:00Z',
    terms: [
      {
        id: 'term-1',
        deal_id: '1',
        category_id: 'cat-1',
        term_key: 'facility_amount',
        term_label: 'Facility Amount',
        value_type: 'currency_amount',
        current_value: 500000000,
        current_value_text: 'USD 500,000,000',
        original_value: 450000000,
        original_value_text: 'USD 450,000,000',
        negotiation_status: 'agreed',
        is_locked: true,
        display_order: 1,
        pending_proposals_count: 0,
        comments_count: 2,
        deadline: null, // Already agreed, no deadline needed
      },
      {
        id: 'term-2',
        deal_id: '1',
        category_id: 'cat-1',
        term_key: 'maturity_date',
        term_label: 'Maturity Date',
        value_type: 'date',
        current_value: '2029-12-15',
        current_value_text: 'December 15, 2029',
        original_value: '2028-06-30',
        original_value_text: 'June 30, 2028',
        negotiation_status: 'under_discussion',
        is_locked: false,
        display_order: 2,
        pending_proposals_count: 1,
        comments_count: 5,
        deadline: getRelativeDate(3), // Due in 3 days
      },
      {
        id: 'term-3',
        deal_id: '1',
        category_id: 'cat-1',
        term_key: 'amortization',
        term_label: 'Amortization Schedule',
        value_type: 'text',
        current_value: 'Quarterly, 1% per annum',
        current_value_text: 'Quarterly, 1% per annum',
        original_value: 'Quarterly, 1% per annum',
        original_value_text: 'Quarterly, 1% per annum',
        negotiation_status: 'proposed',
        is_locked: false,
        display_order: 3,
        pending_proposals_count: 2,
        comments_count: 3,
        deadline: getRelativeDate(-2), // Overdue by 2 days
      },
    ],
  },
  {
    id: 'cat-2',
    deal_id: '1',
    name: 'Pricing Terms',
    display_order: 2,
    parent_category_id: null,
    created_at: '2024-12-01T10:00:00Z',
    terms: [
      {
        id: 'term-8',
        deal_id: '1',
        category_id: 'cat-2',
        term_key: 'credit_rating',
        term_label: 'Credit Rating',
        value_type: 'text',
        current_value: 'BBB',
        current_value_text: 'BBB (S&P)',
        original_value: 'BBB-',
        original_value_text: 'BBB- (S&P)',
        negotiation_status: 'proposed',
        is_locked: false,
        display_order: 0,
        pending_proposals_count: 1,
        comments_count: 3,
        deadline: getRelativeDate(7), // Due in a week
      },
      {
        id: 'term-4',
        deal_id: '1',
        category_id: 'cat-2',
        term_key: 'margin',
        term_label: 'Interest Margin',
        value_type: 'percentage',
        current_value: 2.5,
        current_value_text: '2.50%',
        original_value: 3.0,
        original_value_text: '3.00%',
        negotiation_status: 'under_discussion',
        is_locked: false,
        display_order: 1,
        pending_proposals_count: 1,
        comments_count: 8,
        deadline: getRelativeDate(0), // Due today
      },
      {
        id: 'term-5',
        deal_id: '1',
        category_id: 'cat-2',
        term_key: 'commitment_fee',
        term_label: 'Commitment Fee',
        value_type: 'percentage',
        current_value: 0.35,
        current_value_text: '0.35%',
        original_value: 0.35,
        original_value_text: '0.35%',
        negotiation_status: 'agreed',
        is_locked: false,
        display_order: 2,
        pending_proposals_count: 0,
        comments_count: 1,
        deadline: null, // Already agreed
      },
    ],
  },
  {
    id: 'cat-3',
    deal_id: '1',
    name: 'Financial Covenants',
    display_order: 3,
    parent_category_id: null,
    created_at: '2024-12-01T10:00:00Z',
    terms: [
      {
        id: 'term-6',
        deal_id: '1',
        category_id: 'cat-3',
        term_key: 'leverage_ratio',
        term_label: 'Maximum Leverage Ratio',
        value_type: 'number',
        current_value: 4.0,
        current_value_text: '4.00x',
        original_value: 4.0,
        original_value_text: '4.00x',
        negotiation_status: 'not_started',
        is_locked: false,
        display_order: 1,
        pending_proposals_count: 0,
        comments_count: 0,
        deadline: getRelativeDate(14), // Due in 2 weeks
      },
      {
        id: 'term-7',
        deal_id: '1',
        category_id: 'cat-3',
        term_key: 'interest_coverage',
        term_label: 'Minimum Interest Coverage',
        value_type: 'number',
        current_value: 3.0,
        current_value_text: '3.00x',
        original_value: 2.5,
        original_value_text: '2.50x',
        negotiation_status: 'proposed',
        is_locked: false,
        display_order: 2,
        pending_proposals_count: 1,
        comments_count: 2,
        deadline: getRelativeDate(5), // Due in 5 days
      },
    ],
  },
];

export const mockParticipants: DealParticipant[] = [
  {
    id: 'p-1',
    deal_id: '1',
    user_id: 'user-1',
    party_name: 'Apollo Holdings LLC',
    party_type: 'borrower_side',
    party_role: 'Borrower',
    deal_role: 'deal_lead',
    can_approve: true,
    status: 'active',
    invited_at: '2024-12-01T10:00:00Z',
    joined_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'p-2',
    deal_id: '1',
    user_id: 'user-2',
    party_name: 'BigBank NA',
    party_type: 'lender_side',
    party_role: 'Administrative Agent',
    deal_role: 'deal_lead',
    can_approve: true,
    status: 'active',
    invited_at: '2024-12-01T10:30:00Z',
    joined_at: '2024-12-01T11:00:00Z',
  },
  {
    id: 'p-3',
    deal_id: '1',
    user_id: 'user-3',
    party_name: 'Capital Partners Fund',
    party_type: 'lender_side',
    party_role: 'Syndicate Member',
    deal_role: 'negotiator',
    can_approve: false,
    status: 'active',
    invited_at: '2024-12-02T09:00:00Z',
    joined_at: '2024-12-02T10:00:00Z',
  },
];

export const mockFacilities = [
  { id: 'fac-1', name: 'Term Loan A - Project Apollo', date: '2024-10-15' },
  { id: 'fac-2', name: 'Revolving Credit Facility - XYZ Corp', date: '2024-09-20' },
  { id: 'fac-3', name: 'Senior Secured Term Loan - Neptune Holdings', date: '2024-08-10' },
];

// Single deal for detail page with computed deadline stats
const deadlineStats = calculateDeadlineStatsFromCategories(mockCategories);
export const mockDeal: DealWithStats = {
  ...mockDeals[0],
  stats: {
    ...mockDeals[0].stats!,
    deadline_stats: deadlineStats,
  },
};
