import type { LiveCovenant, HeadroomAlert, DataIntegration, LiveTestingStats } from './types';

/**
 * Mock live covenants with real-time data.
 */
export const mockLiveCovenants: LiveCovenant[] = [
  {
    id: 'lc-001',
    name: 'Total Leverage Ratio',
    covenant_type: 'leverage_ratio',
    facility_id: 'fac-001',
    facility_name: 'Term Loan A - $50M',
    borrower_name: 'Acme Manufacturing Corp',
    threshold_type: 'maximum',
    current_threshold: 4.0,
    current_value: 3.85,
    current_headroom_percentage: 3.75,
    current_headroom_absolute: 0.15,
    last_calculated_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    headroom_24h_ago: 5.2,
    headroom_7d_ago: 8.5,
    headroom_30d_ago: 12.3,
    trend_direction: 'declining',
    velocity_percentage_per_day: -0.28,
    projected_headroom_7d: 1.8,
    projected_headroom_30d: -3.5,
    estimated_breach_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    integration_id: 'int-001',
    integration_status: 'active',
    data_freshness_minutes: 5,
    active_alerts: [],
    alert_count_24h: 3,
  },
  {
    id: 'lc-002',
    name: 'Interest Coverage Ratio',
    covenant_type: 'interest_coverage',
    facility_id: 'fac-002',
    facility_name: 'Revolver - $25M',
    borrower_name: 'TechVentures Inc',
    threshold_type: 'minimum',
    current_threshold: 3.0,
    current_value: 3.32,
    current_headroom_percentage: 10.7,
    current_headroom_absolute: 0.32,
    last_calculated_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    headroom_24h_ago: 11.5,
    headroom_7d_ago: 13.8,
    headroom_30d_ago: 18.2,
    trend_direction: 'declining',
    velocity_percentage_per_day: -0.11,
    projected_headroom_7d: 9.9,
    projected_headroom_30d: 7.4,
    estimated_breach_date: null,
    integration_id: 'int-002',
    integration_status: 'active',
    data_freshness_minutes: 2,
    active_alerts: [],
    alert_count_24h: 1,
  },
  {
    id: 'lc-003',
    name: 'Fixed Charge Coverage Ratio',
    covenant_type: 'fixed_charge_coverage',
    facility_id: 'fac-003',
    facility_name: 'Term Loan B - $75M',
    borrower_name: 'GreenEnergy Solutions LLC',
    threshold_type: 'minimum',
    current_threshold: 1.25,
    current_value: 1.47,
    current_headroom_percentage: 17.6,
    current_headroom_absolute: 0.22,
    last_calculated_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    headroom_24h_ago: 17.1,
    headroom_7d_ago: 16.8,
    headroom_30d_ago: 15.5,
    trend_direction: 'improving',
    velocity_percentage_per_day: 0.07,
    projected_headroom_7d: 18.1,
    projected_headroom_30d: 19.7,
    estimated_breach_date: null,
    integration_id: 'int-003',
    integration_status: 'active',
    data_freshness_minutes: 15,
    active_alerts: [],
    alert_count_24h: 0,
  },
  {
    id: 'lc-004',
    name: 'Minimum Liquidity',
    covenant_type: 'minimum_liquidity',
    facility_id: 'fac-004',
    facility_name: 'ABL Facility - $30M',
    borrower_name: 'RetailCo Holdings',
    threshold_type: 'minimum',
    current_threshold: 5000000,
    current_value: 5225000,
    current_headroom_percentage: 4.5,
    current_headroom_absolute: 225000,
    last_calculated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    headroom_24h_ago: 6.8,
    headroom_7d_ago: 9.2,
    headroom_30d_ago: 14.5,
    trend_direction: 'declining',
    velocity_percentage_per_day: -0.33,
    projected_headroom_7d: 2.2,
    projected_headroom_30d: -5.4,
    estimated_breach_date: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    integration_id: 'int-004',
    integration_status: 'active',
    data_freshness_minutes: 10,
    active_alerts: [],
    alert_count_24h: 2,
  },
  {
    id: 'lc-005',
    name: 'Senior Leverage Ratio',
    covenant_type: 'leverage_ratio',
    facility_id: 'fac-005',
    facility_name: 'Delayed Draw - $40M',
    borrower_name: 'HealthServices Partners',
    threshold_type: 'maximum',
    current_threshold: 3.5,
    current_value: 2.98,
    current_headroom_percentage: 14.9,
    current_headroom_absolute: 0.52,
    last_calculated_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    headroom_24h_ago: 14.2,
    headroom_7d_ago: 15.8,
    headroom_30d_ago: 18.9,
    trend_direction: 'stable',
    velocity_percentage_per_day: -0.02,
    projected_headroom_7d: 14.8,
    projected_headroom_30d: 14.3,
    estimated_breach_date: null,
    integration_id: 'int-005',
    integration_status: 'active',
    data_freshness_minutes: 8,
    active_alerts: [],
    alert_count_24h: 0,
  },
  {
    id: 'lc-006',
    name: 'Debt Service Coverage Ratio',
    covenant_type: 'debt_service_coverage',
    facility_id: 'fac-006',
    facility_name: 'Bridge Loan - $20M',
    borrower_name: 'PropDev Group',
    threshold_type: 'minimum',
    current_threshold: 1.1,
    current_value: 1.36,
    current_headroom_percentage: 23.6,
    current_headroom_absolute: 0.26,
    last_calculated_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    headroom_24h_ago: 22.8,
    headroom_7d_ago: 21.5,
    headroom_30d_ago: 19.2,
    trend_direction: 'improving',
    velocity_percentage_per_day: 0.15,
    projected_headroom_7d: 24.7,
    projected_headroom_30d: 28.1,
    estimated_breach_date: null,
    integration_id: null,
    integration_status: 'inactive',
    data_freshness_minutes: 3,
    active_alerts: [],
    alert_count_24h: 0,
  },
];

/**
 * Mock recent headroom alerts.
 */
export const mockRecentAlerts: HeadroomAlert[] = [
  {
    id: 'alert-001',
    covenant_id: 'lc-001',
    covenant_name: 'Total Leverage Ratio',
    facility_name: 'Term Loan A - $50M',
    borrower_name: 'Acme Manufacturing Corp',
    severity: 'critical',
    alert_type: 'threshold_crossed',
    current_headroom: 3.75,
    threshold_crossed: 5,
    previous_headroom: 5.2,
    change_percentage: -27.9,
    title: 'Critical: Headroom Below 5%',
    message: 'Total Leverage Ratio headroom dropped below 5% threshold',
    recommendation: 'Immediate review recommended. Consider requesting updated financials and discussing cash flow projections with borrower.',
    triggered_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    acknowledged: false,
    acknowledged_at: null,
    acknowledged_by: null,
    notifications_sent: ['email', 'sms', 'slack'],
    notification_sent_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-002',
    covenant_id: 'lc-004',
    covenant_name: 'Minimum Liquidity',
    facility_name: 'ABL Facility - $30M',
    borrower_name: 'RetailCo Holdings',
    severity: 'critical',
    alert_type: 'threshold_crossed',
    current_headroom: 4.5,
    threshold_crossed: 5,
    previous_headroom: 6.8,
    change_percentage: -33.8,
    title: 'Critical: Liquidity Headroom Below 5%',
    message: 'Minimum Liquidity covenant headroom dropped below 5% critical threshold',
    recommendation: 'Urgent: Schedule call with CFO to review cash position and AR/AP aging.',
    triggered_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    acknowledged: false,
    acknowledged_at: null,
    acknowledged_by: null,
    notifications_sent: ['email', 'sms', 'slack'],
    notification_sent_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-003',
    covenant_id: 'lc-002',
    covenant_name: 'Interest Coverage Ratio',
    facility_name: 'Revolver - $25M',
    borrower_name: 'TechVentures Inc',
    severity: 'high',
    alert_type: 'threshold_crossed',
    current_headroom: 10.7,
    threshold_crossed: 10,
    previous_headroom: 11.5,
    change_percentage: -7.0,
    title: 'Warning: Headroom Below 10%',
    message: 'Interest Coverage Ratio headroom crossed below 10% threshold',
    recommendation: 'Monitor closely. Review EBITDA trends and upcoming debt service obligations.',
    triggered_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    acknowledged: true,
    acknowledged_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    acknowledged_by: 'john.doe@lender.com',
    notifications_sent: ['email', 'in_app'],
    notification_sent_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-004',
    covenant_id: 'lc-001',
    covenant_name: 'Total Leverage Ratio',
    facility_name: 'Term Loan A - $50M',
    borrower_name: 'Acme Manufacturing Corp',
    severity: 'high',
    alert_type: 'rapid_decline',
    current_headroom: 3.75,
    threshold_crossed: 0,
    previous_headroom: 8.5,
    change_percentage: -55.9,
    title: 'Rapid Decline Alert',
    message: 'Headroom declined 55.9% over the past 7 days',
    recommendation: 'Investigate cause of rapid deterioration. Review recent financial statements and operating metrics.',
    triggered_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    acknowledged: true,
    acknowledged_at: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    acknowledged_by: 'sarah.smith@lender.com',
    notifications_sent: ['email', 'slack'],
    notification_sent_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-005',
    covenant_id: 'lc-004',
    covenant_name: 'Minimum Liquidity',
    facility_name: 'ABL Facility - $30M',
    borrower_name: 'RetailCo Holdings',
    severity: 'critical',
    alert_type: 'breach_imminent',
    current_headroom: 4.5,
    threshold_crossed: 5,
    previous_headroom: null,
    change_percentage: null,
    title: 'Breach Predicted Within 21 Days',
    message: 'Based on current trajectory, covenant breach estimated in 21 days',
    recommendation: 'Critical: Initiate proactive discussions with borrower. Consider amendment or waiver request.',
    triggered_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    acknowledged: false,
    acknowledged_at: null,
    acknowledged_by: null,
    notifications_sent: ['email', 'sms', 'slack'],
    notification_sent_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
];

/**
 * Mock data integrations.
 */
export const mockIntegrations: DataIntegration[] = [
  {
    id: 'int-001',
    provider: 'quickbooks',
    provider_name: 'QuickBooks Online',
    borrower_id: 'bor-001',
    borrower_name: 'Acme Manufacturing Corp',
    facility_id: 'fac-001',
    facility_name: 'Term Loan A - $50M',
    status: 'active',
    last_sync_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    next_sync_at: new Date(Date.now() + 55 * 60 * 1000).toISOString(),
    sync_frequency: 'hourly',
    api_credentials_valid: true,
    error_message: null,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'int-002',
    provider: 'netsuite',
    provider_name: 'NetSuite',
    borrower_id: 'bor-002',
    borrower_name: 'TechVentures Inc',
    facility_id: 'fac-002',
    facility_name: 'Revolver - $25M',
    status: 'active',
    last_sync_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    next_sync_at: new Date(Date.now() + 58 * 60 * 1000).toISOString(),
    sync_frequency: 'hourly',
    api_credentials_valid: true,
    error_message: null,
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'int-003',
    provider: 'sage',
    provider_name: 'Sage Intacct',
    borrower_id: 'bor-003',
    borrower_name: 'GreenEnergy Solutions LLC',
    facility_id: 'fac-003',
    facility_name: 'Term Loan B - $75M',
    status: 'active',
    last_sync_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    next_sync_at: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    sync_frequency: 'hourly',
    api_credentials_valid: true,
    error_message: null,
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'int-004',
    provider: 'xero',
    provider_name: 'Xero',
    borrower_id: 'bor-004',
    borrower_name: 'RetailCo Holdings',
    facility_id: 'fac-004',
    facility_name: 'ABL Facility - $30M',
    status: 'active',
    last_sync_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    next_sync_at: new Date(Date.now() + 50 * 60 * 1000).toISOString(),
    sync_frequency: 'hourly',
    api_credentials_valid: true,
    error_message: null,
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'int-005',
    provider: 'quickbooks',
    provider_name: 'QuickBooks Online',
    borrower_id: 'bor-005',
    borrower_name: 'HealthServices Partners',
    facility_id: 'fac-005',
    facility_name: 'Delayed Draw - $40M',
    status: 'active',
    last_sync_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    next_sync_at: new Date(Date.now() + 52 * 60 * 1000).toISOString(),
    sync_frequency: 'hourly',
    api_credentials_valid: true,
    error_message: null,
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'int-006',
    provider: 'custom_api',
    provider_name: 'Custom API',
    borrower_id: 'bor-006',
    borrower_name: 'PropDev Group',
    facility_id: 'fac-006',
    facility_name: 'Bridge Loan - $20M',
    status: 'error',
    last_sync_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    next_sync_at: null,
    sync_frequency: 'daily',
    api_credentials_valid: false,
    error_message: 'API authentication failed. Please update credentials.',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

/**
 * Mock dashboard statistics.
 */
export const mockLiveTestingStats: LiveTestingStats = {
  total_covenants: 6,
  covenants_monitored_live: 5,
  covenants_critical: 2,
  covenants_warning: 1,
  covenants_healthy: 3,
  active_integrations: 5,
  total_integrations: 6,
  integrations_with_errors: 1,
  alerts_last_24h: 5,
  alerts_unacknowledged: 3,
  last_sync_timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  next_scheduled_sync: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
};
